//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;

    using IIS.Synchronizer;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЧленСемьи.
    /// </summary>
    // *** Start programmer edit section *** (ChlenSemi CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (ChlenSemi CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "IdentifikDannyeLeechnosti",
            "Shkolnik",
            "Zaiavlenie",
            "RodstvOtn",
            "Leechnost"})]
    [View("ChlenSemi", new string[] {
            "IdentifikDannyeLeechnosti as \'Идентификационные данные личности\'",
            "Shkolnik as \'Статус ребенка\'",
            "Leechnost as \'Фамилия\'"})]
    public class ChlenSemi : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields, ISync
    {
        
        private string fIdentifikDannyeLeechnosti;
        
        private Iis.Eais.GosUslugi.tStatusUchashchegosia fShkolnik;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Iis.Eais.GosUslugi.RodstvOtn fRodstvOtn;
        
        private Iis.Eais.GosUslugi.Leechnost fLeechnost;
        
        private Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu fZaiavlenie;
        
        // *** Start programmer edit section *** (ChlenSemi CustomMembers)

        // *** End programmer edit section *** (ChlenSemi CustomMembers)

        
        /// <summary>
        /// IdentifikDannyeLeechnosti.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti CustomAttributes)
        public virtual string IdentifikDannyeLeechnosti
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Get start)

                // *** End programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Get start)
                string result = this.fIdentifikDannyeLeechnosti;
                // *** Start programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Get end)

                // *** End programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Set start)

                // *** End programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Set start)
                this.fIdentifikDannyeLeechnosti = value;
                // *** Start programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Set end)

                // *** End programmer edit section *** (ChlenSemi.IdentifikDannyeLeechnosti Set end)
            }
        }
        
        /// <summary>
        /// Shkolnik.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.Shkolnik CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.Shkolnik CustomAttributes)
        public virtual Iis.Eais.GosUslugi.tStatusUchashchegosia Shkolnik
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.Shkolnik Get start)

                // *** End programmer edit section *** (ChlenSemi.Shkolnik Get start)
                Iis.Eais.GosUslugi.tStatusUchashchegosia result = this.fShkolnik;
                // *** Start programmer edit section *** (ChlenSemi.Shkolnik Get end)

                // *** End programmer edit section *** (ChlenSemi.Shkolnik Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.Shkolnik Set start)

                // *** End programmer edit section *** (ChlenSemi.Shkolnik Set start)
                this.fShkolnik = value;
                // *** Start programmer edit section *** (ChlenSemi.Shkolnik Set end)

                // *** End programmer edit section *** (ChlenSemi.Shkolnik Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.CreateTime Get start)

                // *** End programmer edit section *** (ChlenSemi.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ChlenSemi.CreateTime Get end)

                // *** End programmer edit section *** (ChlenSemi.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.CreateTime Set start)

                // *** End programmer edit section *** (ChlenSemi.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ChlenSemi.CreateTime Set end)

                // *** End programmer edit section *** (ChlenSemi.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.Creator CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.Creator Get start)

                // *** End programmer edit section *** (ChlenSemi.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ChlenSemi.Creator Get end)

                // *** End programmer edit section *** (ChlenSemi.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.Creator Set start)

                // *** End programmer edit section *** (ChlenSemi.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ChlenSemi.Creator Set end)

                // *** End programmer edit section *** (ChlenSemi.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.EditTime CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.EditTime Get start)

                // *** End programmer edit section *** (ChlenSemi.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ChlenSemi.EditTime Get end)

                // *** End programmer edit section *** (ChlenSemi.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.EditTime Set start)

                // *** End programmer edit section *** (ChlenSemi.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ChlenSemi.EditTime Set end)

                // *** End programmer edit section *** (ChlenSemi.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.Editor CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.Editor Get start)

                // *** End programmer edit section *** (ChlenSemi.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ChlenSemi.Editor Get end)

                // *** End programmer edit section *** (ChlenSemi.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.Editor Set start)

                // *** End programmer edit section *** (ChlenSemi.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ChlenSemi.Editor Set end)

                // *** End programmer edit section *** (ChlenSemi.Editor Set end)
            }
        }
        
        /// <summary>
        /// ЧленСемьи.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.RodstvOtn CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.RodstvOtn CustomAttributes)
        [PropertyStorage(new string[] {
                "RodstvOtn"})]
        public virtual Iis.Eais.GosUslugi.RodstvOtn RodstvOtn
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.RodstvOtn Get start)

                // *** End programmer edit section *** (ChlenSemi.RodstvOtn Get start)
                Iis.Eais.GosUslugi.RodstvOtn result = this.fRodstvOtn;
                // *** Start programmer edit section *** (ChlenSemi.RodstvOtn Get end)

                // *** End programmer edit section *** (ChlenSemi.RodstvOtn Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.RodstvOtn Set start)

                // *** End programmer edit section *** (ChlenSemi.RodstvOtn Set start)
                this.fRodstvOtn = value;
                // *** Start programmer edit section *** (ChlenSemi.RodstvOtn Set end)

                // *** End programmer edit section *** (ChlenSemi.RodstvOtn Set end)
            }
        }
        
        /// <summary>
        /// ЧленСемьи.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.Leechnost CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.Leechnost CustomAttributes)
        [PropertyStorage(new string[] {
                "Leechnost"})]
        public virtual Iis.Eais.GosUslugi.Leechnost Leechnost
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.Leechnost Get start)

                // *** End programmer edit section *** (ChlenSemi.Leechnost Get start)
                Iis.Eais.GosUslugi.Leechnost result = this.fLeechnost;
                // *** Start programmer edit section *** (ChlenSemi.Leechnost Get end)

                // *** End programmer edit section *** (ChlenSemi.Leechnost Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.Leechnost Set start)

                // *** End programmer edit section *** (ChlenSemi.Leechnost Set start)
                this.fLeechnost = value;
                // *** Start programmer edit section *** (ChlenSemi.Leechnost Set end)

                // *** End programmer edit section *** (ChlenSemi.Leechnost Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu.
        /// </summary>
        // *** Start programmer edit section *** (ChlenSemi.Zaiavlenie CustomAttributes)

        // *** End programmer edit section *** (ChlenSemi.Zaiavlenie CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Zaiavlenie"})]
        public virtual Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu Zaiavlenie
        {
            get
            {
                // *** Start programmer edit section *** (ChlenSemi.Zaiavlenie Get start)

                // *** End programmer edit section *** (ChlenSemi.Zaiavlenie Get start)
                Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu result = this.fZaiavlenie;
                // *** Start programmer edit section *** (ChlenSemi.Zaiavlenie Get end)

                // *** End programmer edit section *** (ChlenSemi.Zaiavlenie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ChlenSemi.Zaiavlenie Set start)

                // *** End programmer edit section *** (ChlenSemi.Zaiavlenie Set start)
                this.fZaiavlenie = value;
                // *** Start programmer edit section *** (ChlenSemi.Zaiavlenie Set end)

                // *** End programmer edit section *** (ChlenSemi.Zaiavlenie Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.GosUslugi.ChlenSemi));
                }
            }
            
            /// <summary>
            /// "ChlenSemi" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ChlenSemi
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ChlenSemi", typeof(Iis.Eais.GosUslugi.ChlenSemi));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of ChlenSemi.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfChlenSemi CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (DetailArrayDetailArrayOfChlenSemi CustomAttributes)
    public class DetailArrayOfChlenSemi : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfChlenSemi members)

        // *** End programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfChlenSemi members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ChlenSemi by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ChlenSemi.
        /// </summary>
        public DetailArrayOfChlenSemi(Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu fZaiavlenieNaGosUslugu) : 
                base(typeof(ChlenSemi), ((ICSSoft.STORMNET.DataObject)(fZaiavlenieNaGosUslugu)))
        {
        }
        
        public Iis.Eais.GosUslugi.ChlenSemi this[int index]
        {
            get
            {
                return ((Iis.Eais.GosUslugi.ChlenSemi)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Iis.Eais.GosUslugi.ChlenSemi dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
