//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДокументПоУслуге.
    /// </summary>
    // *** Start programmer edit section *** (DokumentPoUsluge CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (DokumentPoUsluge CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Fail",
            "Zaiavlenie"})]
    [View("DokumentPoUsluge", new string[] {
            "Fail as \'Файл\'"})]
    public class DokumentPoUsluge : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fFail;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu fZaiavlenie;
        
        // *** Start programmer edit section *** (DokumentPoUsluge CustomMembers)

        // *** End programmer edit section *** (DokumentPoUsluge CustomMembers)

        
        /// <summary>
        /// Fail.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.Fail CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.Fail CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile Fail
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Fail Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.Fail Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fFail;
                // *** Start programmer edit section *** (DokumentPoUsluge.Fail Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.Fail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Fail Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.Fail Set start)
                this.fFail = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.Fail Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.Fail Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.CreateTime CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.CreateTime Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (DokumentPoUsluge.CreateTime Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.CreateTime Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.CreateTime Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.Creator CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Creator Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (DokumentPoUsluge.Creator Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Creator Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.Creator Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.EditTime CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.EditTime Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (DokumentPoUsluge.EditTime Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.EditTime Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.EditTime Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.Editor CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Editor Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (DokumentPoUsluge.Editor Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Editor Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.Editor Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu.
        /// </summary>
        // *** Start programmer edit section *** (DokumentPoUsluge.Zaiavlenie CustomAttributes)

        // *** End programmer edit section *** (DokumentPoUsluge.Zaiavlenie CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Zaiavlenie"})]
        public virtual Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu Zaiavlenie
        {
            get
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Zaiavlenie Get start)

                // *** End programmer edit section *** (DokumentPoUsluge.Zaiavlenie Get start)
                Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu result = this.fZaiavlenie;
                // *** Start programmer edit section *** (DokumentPoUsluge.Zaiavlenie Get end)

                // *** End programmer edit section *** (DokumentPoUsluge.Zaiavlenie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DokumentPoUsluge.Zaiavlenie Set start)

                // *** End programmer edit section *** (DokumentPoUsluge.Zaiavlenie Set start)
                this.fZaiavlenie = value;
                // *** Start programmer edit section *** (DokumentPoUsluge.Zaiavlenie Set end)

                // *** End programmer edit section *** (DokumentPoUsluge.Zaiavlenie Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.GosUslugi.DokumentPoUsluge));
                }
            }
            
            /// <summary>
            /// "DokumentPoUsluge" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DokumentPoUsluge
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DokumentPoUsluge", typeof(Iis.Eais.GosUslugi.DokumentPoUsluge));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of DokumentPoUsluge.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDokumentPoUsluge CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (DetailArrayDetailArrayOfDokumentPoUsluge CustomAttributes)
    public class DetailArrayOfDokumentPoUsluge : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfDokumentPoUsluge members)

        // *** End programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfDokumentPoUsluge members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DokumentPoUsluge by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DokumentPoUsluge.
        /// </summary>
        public DetailArrayOfDokumentPoUsluge(Iis.Eais.GosUslugi.ZaiavlenieNaGosUslugu fZaiavlenieNaGosUslugu) : 
                base(typeof(DokumentPoUsluge), ((ICSSoft.STORMNET.DataObject)(fZaiavlenieNaGosUslugu)))
        {
        }
        
        public Iis.Eais.GosUslugi.DokumentPoUsluge this[int index]
        {
            get
            {
                return ((Iis.Eais.GosUslugi.DokumentPoUsluge)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Iis.Eais.GosUslugi.DokumentPoUsluge dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
