//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;

    using IIS.Synchronizer;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ГосУслуга.
    /// </summary>
    // *** Start programmer edit section *** (GosUsluga CustomAttributes)
    [Serializable]
    [Primary(true)]
    // *** End programmer edit section *** (GosUsluga CustomAttributes)
    [BusinessServer("Iis.Eais.GosUslugi.GosUslugaBS, Eais.GosUslugi.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Gos usluga")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "PolnoeNaimenovanie as \'Полное наименование\'",
            "PlanSrokIsp as \'Плановый срок исполнения (дней)\'"})]
    [AssociatedDetailViewAttribute("AuditView", "Statusy", "AuditView", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("AuditView", "Conditions", "AuditView", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("AuditView", "Requests", "AuditView", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("AuditView", "Steps", "AuditView", true, "", "", true, new string[] {
            ""})]
    [View("GosUslugaE", new string[] {
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "PolnoeNaimenovanie as \'Полное наименование\'",
            "PlanSrokIsp as \'Плановый срок исполнения (дней)\'"})]
    [AssociatedDetailViewAttribute("GosUslugaE", "Statusy", "StatusyGUE", true, "", "Статусы ГУ", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("GosUslugaE", "Conditions", "WorkflowConditionGUD", true, "", "Условия", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("GosUslugaE", "Requests", "MVRequestGUD", true, "", "Запросы МВ", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("GosUslugaE", "Steps", "WorkflowStepGUD", true, "", "Этапы", true, new string[] {
            ""})]
    [View("GosUslugaL", new string[] {
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "PolnoeNaimenovanie as \'Полное наименование\'",
            "PlanSrokIsp as \'Плановый срок исполнения (дней)\'"})]
    [AssociatedDetailViewAttribute("GosUslugaL", "Statusy", "StatusyGUL", true, "", "Статусы ГУ", true, new string[] {
            ""})]
    public class GosUsluga : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields, ISync
    {
        
        private string fKratkoeNaimenovanie;
        
        private string fPolnoeNaimenovanie;
        
        private int fPlanSrokIsp;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Iis.Eais.GosUslugi.DetailArrayOfStatusyGU fStatusy;
        
        private Iis.Eais.GosUslugi.DetailArrayOfWorkflowStepGU fSteps;
        
        private Iis.Eais.GosUslugi.DetailArrayOfMVRequestGU fRequests;
        
        private Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU fConditions;
        
        // *** Start programmer edit section *** (GosUsluga CustomMembers)

        // *** End programmer edit section *** (GosUsluga CustomMembers)

        
        /// <summary>
        /// Краткое наименование.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.KratkoeNaimenovanie CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.KratkoeNaimenovanie CustomAttributes)
        [StrLen(100)]
        [NotNull()]
        public virtual string KratkoeNaimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.KratkoeNaimenovanie Get start)

                // *** End programmer edit section *** (GosUsluga.KratkoeNaimenovanie Get start)
                string result = this.fKratkoeNaimenovanie;
                // *** Start programmer edit section *** (GosUsluga.KratkoeNaimenovanie Get end)

                // *** End programmer edit section *** (GosUsluga.KratkoeNaimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.KratkoeNaimenovanie Set start)

                // *** End programmer edit section *** (GosUsluga.KratkoeNaimenovanie Set start)
                this.fKratkoeNaimenovanie = value;
                // *** Start programmer edit section *** (GosUsluga.KratkoeNaimenovanie Set end)

                // *** End programmer edit section *** (GosUsluga.KratkoeNaimenovanie Set end)
            }
        }
        
        /// <summary>
        /// Полное наименование.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.PolnoeNaimenovanie CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.PolnoeNaimenovanie CustomAttributes)
        [StrLen(1000)]
        [NotNull()]
        public virtual string PolnoeNaimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.PolnoeNaimenovanie Get start)

                // *** End programmer edit section *** (GosUsluga.PolnoeNaimenovanie Get start)
                string result = this.fPolnoeNaimenovanie;
                // *** Start programmer edit section *** (GosUsluga.PolnoeNaimenovanie Get end)

                // *** End programmer edit section *** (GosUsluga.PolnoeNaimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.PolnoeNaimenovanie Set start)

                // *** End programmer edit section *** (GosUsluga.PolnoeNaimenovanie Set start)
                this.fPolnoeNaimenovanie = value;
                // *** Start programmer edit section *** (GosUsluga.PolnoeNaimenovanie Set end)

                // *** End programmer edit section *** (GosUsluga.PolnoeNaimenovanie Set end)
            }
        }
        
        /// <summary>
        /// Плановый срок исполнения.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.PlanSrokIsp CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.PlanSrokIsp CustomAttributes)
        [NotNull()]
        public virtual int PlanSrokIsp
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.PlanSrokIsp Get start)

                // *** End programmer edit section *** (GosUsluga.PlanSrokIsp Get start)
                int result = this.fPlanSrokIsp;
                // *** Start programmer edit section *** (GosUsluga.PlanSrokIsp Get end)

                // *** End programmer edit section *** (GosUsluga.PlanSrokIsp Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.PlanSrokIsp Set start)

                // *** End programmer edit section *** (GosUsluga.PlanSrokIsp Set start)
                this.fPlanSrokIsp = value;
                // *** Start programmer edit section *** (GosUsluga.PlanSrokIsp Set end)

                // *** End programmer edit section *** (GosUsluga.PlanSrokIsp Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.CreateTime CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.CreateTime Get start)

                // *** End programmer edit section *** (GosUsluga.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (GosUsluga.CreateTime Get end)

                // *** End programmer edit section *** (GosUsluga.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.CreateTime Set start)

                // *** End programmer edit section *** (GosUsluga.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (GosUsluga.CreateTime Set end)

                // *** End programmer edit section *** (GosUsluga.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Creator CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Creator Get start)

                // *** End programmer edit section *** (GosUsluga.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (GosUsluga.Creator Get end)

                // *** End programmer edit section *** (GosUsluga.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Creator Set start)

                // *** End programmer edit section *** (GosUsluga.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (GosUsluga.Creator Set end)

                // *** End programmer edit section *** (GosUsluga.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.EditTime CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.EditTime Get start)

                // *** End programmer edit section *** (GosUsluga.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (GosUsluga.EditTime Get end)

                // *** End programmer edit section *** (GosUsluga.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.EditTime Set start)

                // *** End programmer edit section *** (GosUsluga.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (GosUsluga.EditTime Set end)

                // *** End programmer edit section *** (GosUsluga.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Editor CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Editor Get start)

                // *** End programmer edit section *** (GosUsluga.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (GosUsluga.Editor Get end)

                // *** End programmer edit section *** (GosUsluga.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Editor Set start)

                // *** End programmer edit section *** (GosUsluga.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (GosUsluga.Editor Set end)

                // *** End programmer edit section *** (GosUsluga.Editor Set end)
            }
        }
        
        /// <summary>
        /// ГосУслуга.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Statusy CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Statusy CustomAttributes)
        public virtual Iis.Eais.GosUslugi.DetailArrayOfStatusyGU Statusy
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Statusy Get start)

                // *** End programmer edit section *** (GosUsluga.Statusy Get start)
                if ((this.fStatusy == null))
                {
                    this.fStatusy = new Iis.Eais.GosUslugi.DetailArrayOfStatusyGU(this);
                }
                Iis.Eais.GosUslugi.DetailArrayOfStatusyGU result = this.fStatusy;
                // *** Start programmer edit section *** (GosUsluga.Statusy Get end)

                // *** End programmer edit section *** (GosUsluga.Statusy Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Statusy Set start)

                // *** End programmer edit section *** (GosUsluga.Statusy Set start)
                this.fStatusy = value;
                // *** Start programmer edit section *** (GosUsluga.Statusy Set end)

                // *** End programmer edit section *** (GosUsluga.Statusy Set end)
            }
        }
        
        /// <summary>
        /// ГосУслуга.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Steps CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Steps CustomAttributes)
        public virtual Iis.Eais.GosUslugi.DetailArrayOfWorkflowStepGU Steps
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Steps Get start)

                // *** End programmer edit section *** (GosUsluga.Steps Get start)
                if ((this.fSteps == null))
                {
                    this.fSteps = new Iis.Eais.GosUslugi.DetailArrayOfWorkflowStepGU(this);
                }
                Iis.Eais.GosUslugi.DetailArrayOfWorkflowStepGU result = this.fSteps;
                // *** Start programmer edit section *** (GosUsluga.Steps Get end)

                // *** End programmer edit section *** (GosUsluga.Steps Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Steps Set start)

                // *** End programmer edit section *** (GosUsluga.Steps Set start)
                this.fSteps = value;
                // *** Start programmer edit section *** (GosUsluga.Steps Set end)

                // *** End programmer edit section *** (GosUsluga.Steps Set end)
            }
        }
        
        /// <summary>
        /// ГосУслуга.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Requests CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Requests CustomAttributes)
        public virtual Iis.Eais.GosUslugi.DetailArrayOfMVRequestGU Requests
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Requests Get start)

                // *** End programmer edit section *** (GosUsluga.Requests Get start)
                if ((this.fRequests == null))
                {
                    this.fRequests = new Iis.Eais.GosUslugi.DetailArrayOfMVRequestGU(this);
                }
                Iis.Eais.GosUslugi.DetailArrayOfMVRequestGU result = this.fRequests;
                // *** Start programmer edit section *** (GosUsluga.Requests Get end)

                // *** End programmer edit section *** (GosUsluga.Requests Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Requests Set start)

                // *** End programmer edit section *** (GosUsluga.Requests Set start)
                this.fRequests = value;
                // *** Start programmer edit section *** (GosUsluga.Requests Set end)

                // *** End programmer edit section *** (GosUsluga.Requests Set end)
            }
        }
        
        /// <summary>
        /// ГосУслуга.
        /// </summary>
        // *** Start programmer edit section *** (GosUsluga.Conditions CustomAttributes)

        // *** End programmer edit section *** (GosUsluga.Conditions CustomAttributes)
        public virtual Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU Conditions
        {
            get
            {
                // *** Start programmer edit section *** (GosUsluga.Conditions Get start)

                // *** End programmer edit section *** (GosUsluga.Conditions Get start)
                if ((this.fConditions == null))
                {
                    this.fConditions = new Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU(this);
                }
                Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU result = this.fConditions;
                // *** Start programmer edit section *** (GosUsluga.Conditions Get end)

                // *** End programmer edit section *** (GosUsluga.Conditions Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GosUsluga.Conditions Set start)

                // *** End programmer edit section *** (GosUsluga.Conditions Set start)
                this.fConditions = value;
                // *** Start programmer edit section *** (GosUsluga.Conditions Set end)

                // *** End programmer edit section *** (GosUsluga.Conditions Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.GosUslugi.GosUsluga));
                }
            }
            
            /// <summary>
            /// "GosUslugaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GosUslugaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GosUslugaE", typeof(Iis.Eais.GosUslugi.GosUsluga));
                }
            }
            
            /// <summary>
            /// "GosUslugaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GosUslugaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GosUslugaL", typeof(Iis.Eais.GosUslugi.GosUsluga));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
