//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОрганСЗ.
    /// </summary>
    // *** Start programmer edit section *** (OrganSZ CustomAttributes)
    [Serializable]
    [Primary(true)]
    // *** End programmer edit section *** (OrganSZ CustomAttributes)
    [BusinessServer("Iis.Eais.GosUslugi.OrganSZBS, Eais.GosUslugi.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[0])]
    [View("OrganSZE", new string[0])]
    [View("OrganSZL", new string[0])]
    public class OrganSZ : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (OrganSZ CustomMembers)

        // *** End programmer edit section *** (OrganSZ CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (OrganSZ.CreateTime CustomAttributes)

        // *** End programmer edit section *** (OrganSZ.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (OrganSZ.CreateTime Get start)

                // *** End programmer edit section *** (OrganSZ.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (OrganSZ.CreateTime Get end)

                // *** End programmer edit section *** (OrganSZ.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrganSZ.CreateTime Set start)

                // *** End programmer edit section *** (OrganSZ.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (OrganSZ.CreateTime Set end)

                // *** End programmer edit section *** (OrganSZ.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (OrganSZ.Creator CustomAttributes)

        // *** End programmer edit section *** (OrganSZ.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (OrganSZ.Creator Get start)

                // *** End programmer edit section *** (OrganSZ.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (OrganSZ.Creator Get end)

                // *** End programmer edit section *** (OrganSZ.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrganSZ.Creator Set start)

                // *** End programmer edit section *** (OrganSZ.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (OrganSZ.Creator Set end)

                // *** End programmer edit section *** (OrganSZ.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (OrganSZ.EditTime CustomAttributes)

        // *** End programmer edit section *** (OrganSZ.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (OrganSZ.EditTime Get start)

                // *** End programmer edit section *** (OrganSZ.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (OrganSZ.EditTime Get end)

                // *** End programmer edit section *** (OrganSZ.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrganSZ.EditTime Set start)

                // *** End programmer edit section *** (OrganSZ.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (OrganSZ.EditTime Set end)

                // *** End programmer edit section *** (OrganSZ.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (OrganSZ.Editor CustomAttributes)

        // *** End programmer edit section *** (OrganSZ.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (OrganSZ.Editor Get start)

                // *** End programmer edit section *** (OrganSZ.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (OrganSZ.Editor Get end)

                // *** End programmer edit section *** (OrganSZ.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrganSZ.Editor Set start)

                // *** End programmer edit section *** (OrganSZ.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (OrganSZ.Editor Set end)

                // *** End programmer edit section *** (OrganSZ.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.GosUslugi.OrganSZ));
                }
            }
            
            /// <summary>
            /// "OrganSZE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrganSZE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrganSZE", typeof(Iis.Eais.GosUslugi.OrganSZ));
                }
            }
            
            /// <summary>
            /// "OrganSZL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrganSZL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrganSZL", typeof(Iis.Eais.GosUslugi.OrganSZ));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
