//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// WorkflowConditionGU.
    /// </summary>
    // *** Start programmer edit section *** (WorkflowConditionGU CustomAttributes)
    [Serializable]
    [Primary(true)]
    // *** End programmer edit section *** (WorkflowConditionGU CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "GosUsluga as \'GousUsluga\'",
            "GosUsluga.KratkoeNaimenovanie",
            "Enabled as \'Enabled\'",
            "Condition as \'Condition\'",
            "Condition.Name as \'Name\'"}, Hidden=new string[] {
            "GosUsluga.KratkoeNaimenovanie",
            "Condition.Name"})]
    [MasterViewDefineAttribute("AuditView", "GosUsluga", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "KratkoeNaimenovanie")]
    [MasterViewDefineAttribute("AuditView", "Condition", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("WorkflowConditionGUD", new string[] {
            "GosUsluga",
            "Enabled as \'Активно\'",
            "Condition as \'Условие\'",
            "Condition.Name"}, Hidden=new string[] {
            "GosUsluga",
            "Condition.Name"})]
    [MasterViewDefineAttribute("WorkflowConditionGUD", "Condition", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class WorkflowConditionGU : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private bool fEnabled = true;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private Iis.Eais.GosUslugi.WorkflowCondition fCondition;
        
        private Iis.Eais.GosUslugi.GosUsluga fGosUsluga;
        
        // *** Start programmer edit section *** (WorkflowConditionGU CustomMembers)

        // *** End programmer edit section *** (WorkflowConditionGU CustomMembers)

        
        /// <summary>
        /// Enabled.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.Enabled CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.Enabled CustomAttributes)
        [NotNull()]
        public virtual bool Enabled
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Enabled Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.Enabled Get start)
                bool result = this.fEnabled;
                // *** Start programmer edit section *** (WorkflowConditionGU.Enabled Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.Enabled Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Enabled Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.Enabled Set start)
                this.fEnabled = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.Enabled Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.Enabled Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.CreateTime CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.CreateTime Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (WorkflowConditionGU.CreateTime Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.CreateTime Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.CreateTime Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.Creator CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Creator Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (WorkflowConditionGU.Creator Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Creator Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.Creator Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.EditTime CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.EditTime Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (WorkflowConditionGU.EditTime Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.EditTime Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.EditTime Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.Editor CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Editor Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (WorkflowConditionGU.Editor Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Editor Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.Editor Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.Editor Set end)
            }
        }
        
        /// <summary>
        /// WorkflowConditionGU.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.Condition CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.Condition CustomAttributes)
        [PropertyStorage(new string[] {
                "Condition"})]
        [NotNull()]
        public virtual Iis.Eais.GosUslugi.WorkflowCondition Condition
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Condition Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.Condition Get start)
                Iis.Eais.GosUslugi.WorkflowCondition result = this.fCondition;
                // *** Start programmer edit section *** (WorkflowConditionGU.Condition Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.Condition Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.Condition Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.Condition Set start)
                this.fCondition = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.Condition Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.Condition Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Iis.Eais.GosUslugi.GosUsluga.
        /// </summary>
        // *** Start programmer edit section *** (WorkflowConditionGU.GosUsluga CustomAttributes)

        // *** End programmer edit section *** (WorkflowConditionGU.GosUsluga CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "GosUsluga"})]
        public virtual Iis.Eais.GosUslugi.GosUsluga GosUsluga
        {
            get
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.GosUsluga Get start)

                // *** End programmer edit section *** (WorkflowConditionGU.GosUsluga Get start)
                Iis.Eais.GosUslugi.GosUsluga result = this.fGosUsluga;
                // *** Start programmer edit section *** (WorkflowConditionGU.GosUsluga Get end)

                // *** End programmer edit section *** (WorkflowConditionGU.GosUsluga Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkflowConditionGU.GosUsluga Set start)

                // *** End programmer edit section *** (WorkflowConditionGU.GosUsluga Set start)
                this.fGosUsluga = value;
                // *** Start programmer edit section *** (WorkflowConditionGU.GosUsluga Set end)

                // *** End programmer edit section *** (WorkflowConditionGU.GosUsluga Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.GosUslugi.WorkflowConditionGU));
                }
            }
            
            /// <summary>
            /// "WorkflowConditionGUD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View WorkflowConditionGUD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("WorkflowConditionGUD", typeof(Iis.Eais.GosUslugi.WorkflowConditionGU));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of WorkflowConditionGU.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfWorkflowConditionGU CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (DetailArrayDetailArrayOfWorkflowConditionGU CustomAttributes)
    public class DetailArrayOfWorkflowConditionGU : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU members)

        // *** End programmer edit section *** (Iis.Eais.GosUslugi.DetailArrayOfWorkflowConditionGU members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type WorkflowConditionGU by index.
        /// </summary>
        /// <summary>
        /// Adds object with type WorkflowConditionGU.
        /// </summary>
        public DetailArrayOfWorkflowConditionGU(Iis.Eais.GosUslugi.GosUsluga fGosUsluga) : 
                base(typeof(WorkflowConditionGU), ((ICSSoft.STORMNET.DataObject)(fGosUsluga)))
        {
        }
        
        public Iis.Eais.GosUslugi.WorkflowConditionGU this[int index]
        {
            get
            {
                return ((Iis.Eais.GosUslugi.WorkflowConditionGU)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Iis.Eais.GosUslugi.WorkflowConditionGU dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
