//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Main obj L.
    /// </summary>
    // *** Start programmer edit section *** (MainObjL CustomAttributes)

    // *** End programmer edit section *** (MainObjL CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class MainObjL : ICSSoft.STORMNET.UI.BaseIndpdList
    {
        
        // *** Start programmer edit section *** (MainObjL CustomMembers)

        // *** End programmer edit section *** (MainObjL CustomMembers)

        
        public virtual SimpleTestAuditProject.DPDIMainObjL MainObjLForm
        {
            get
            {
                return ((SimpleTestAuditProject.DPDIMainObjL)(base.EditInitiator));
            }
            set
            {
                base.EditInitiator = ((ICSSoft.STORMNET.UI.IEditInitiator)(value));
            }
        }
        
        public override System.Type GetEditor(ICSSoft.STORMNET.UI.EventType eventtype, ICSSoft.STORMNET.DataObject dataobject, string contpath, string propertyname)
        {
            // *** Start programmer edit section *** (MainObjL.GetEditor(EventType, DataObject, string, string) start)

            // *** End programmer edit section *** (MainObjL.GetEditor(EventType, DataObject, string, string) start)
            System.Type objecttype = dataobject.GetType();
            if ((eventtype == ICSSoft.STORMNET.UI.EventType.Edit))
            {
                if ((objecttype == typeof(SimpleTestAuditProject.MainObj)))
                {
                    return System.Type.GetType("SimpleTestAuditProject.MainObjE,SimpleTestAuditProject(Forms)");
                }
            }
            if ((eventtype == ICSSoft.STORMNET.UI.EventType.New))
            {
                if ((objecttype == typeof(SimpleTestAuditProject.MainObj)))
                {
                    return System.Type.GetType("SimpleTestAuditProject.MainObjE,SimpleTestAuditProject(Forms)");
                }
            }
            throw new ICSSoft.STORMNET.UI.NoSuchContainerException("MainObjL", eventtype, dataobject, contpath, propertyname);
        }
        
        public override System.Type GetEditor(ICSSoft.STORMNET.UI.EventType eventtype, ICSSoft.STORMNET.DataObject dataobject, string contpath, string propertyname, object tag)
        {
            // *** Start programmer edit section *** (MainObjL.GetEditor(EventType, Type, string, string, object) start)

            // *** End programmer edit section *** (MainObjL.GetEditor(EventType, Type, string, string, object) start)
            return this.GetEditor(eventtype, dataobject, contpath, propertyname);
        }
        
        protected override ICSSoft.STORMNET.UI.IEditInitiator GetDpdForm()
        {
            // *** Start programmer edit section *** (MainObjL.GetDpdForm() start)

            // *** End programmer edit section *** (MainObjL.GetDpdForm() start)
            SimpleTestAuditProject.WinformMainObjL form = new SimpleTestAuditProject.WinformMainObjL();
            this.prv_AttachEventsFromDpdForm(form);
            return form;
        }
        
        public override Scriptizer.DataObjects.Script GetScript()
        {
            // *** Start programmer edit section *** (MainObjL.GetScript start)

            // *** End programmer edit section *** (MainObjL.GetScript start)
            Scriptizer.DataObjects.Script script = base.GetScript();
            // *** Start programmer edit section *** (MainObjL.GetScript end)

            // *** End programmer edit section *** (MainObjL.GetScript end)
            return script;
        }
        
        protected virtual void prv_AttachEventsFromDpdForm(object form)
        {
            // *** Start programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))

            // *** End programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))
            SimpleTestAuditProject.DPDIMainObjL typedForm = ((SimpleTestAuditProject.DPDIMainObjL)(form));
        }
    }
    
    /// <summary>
    /// Main obj L.
    /// </summary>
    // *** Start programmer edit section *** (DPDIMainObjL CustomAttributes)

    // *** End programmer edit section *** (DPDIMainObjL CustomAttributes)
    public interface DPDIMainObjL
    {
        
        // *** Start programmer edit section *** (DPDIMainObjL CustomMembers)

        // *** End programmer edit section *** (DPDIMainObjL CustomMembers)

        // *** Start programmer edit section *** (DPDIMainObjL Members)

        // *** End programmer edit section *** (DPDIMainObjL Members)

    }
}
