//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Master obj E.
    /// </summary>
    // *** Start programmer edit section *** (MasterObjE CustomAttributes)

    // *** End programmer edit section *** (MasterObjE CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class MasterObjE : ICSSoft.STORMNET.UI.BaseIndpdEdit
    {
        
        // *** Start programmer edit section *** (MasterObjE CustomMembers)

        // *** End programmer edit section *** (MasterObjE CustomMembers)

        
        public virtual SimpleTestAuditProject.DPDIMasterObjE MasterObjEForm
        {
            get
            {
                return ((SimpleTestAuditProject.DPDIMasterObjE)(base.Editor));
            }
            set
            {
                base.Editor = ((ICSSoft.STORMNET.UI.IEditor)(value));
            }
        }
        
        public override System.Type GetPrinter(ICSSoft.STORMNET.DataObject[] objects, string contpath, string propertyname)
        {
            // *** Start programmer edit section *** (MasterObjE.GetPrinter(DataObject[], string, string) start)

            // *** End programmer edit section *** (MasterObjE.GetPrinter(DataObject[], string, string) start)
            throw new ICSSoft.STORMNET.UI.NoSuchContainerException("MasterObjE", ICSSoft.STORMNET.UI.EventType.Custom, null, contpath, propertyname);
        }
        
        public override System.Type GetEditor(ICSSoft.STORMNET.UI.EventType eventtype, ICSSoft.STORMNET.DataObject dataobject, string contpath, string propertyname, object tag)
        {
            // *** Start programmer edit section *** (MasterObjE.GetEditor(EventType, DataObject, string, string) start)

            // *** End programmer edit section *** (MasterObjE.GetEditor(EventType, DataObject, string, string) start)
            if ((propertyname == "MasterDetail.MasterObj"))
            {
                return System.Type.GetType("SimpleTestAuditProject.MasterObjL,SimpleTestAuditProject(Forms)");
            }
            throw new ICSSoft.STORMNET.UI.NoSuchContainerException("MasterObjE", eventtype, dataobject, contpath, propertyname);
        }
        
        protected override void PrepareDataObjectForEdit(ICSSoft.STORMNET.DataObject dobject)
        {
            // *** Start programmer edit section *** (PrepareDataObjectForEdit (DataObject) start)

            // *** End programmer edit section *** (PrepareDataObjectForEdit (DataObject) start)
            m_objView = ICSSoft.STORMNET.Information.GetView("MasterObjE", typeof(SimpleTestAuditProject.MasterObj));
            if (((dobject.GetStatus(false) != ICSSoft.STORMNET.ObjectStatus.Created) 
                        || dobject.Prototyped))
            {
                ICSSoft.STORMNET.Business.DataServiceProvider.DataService.LoadObject(m_objView, dobject, false, false);
                dobject.InitDataCopy();
            }
            // *** Start programmer edit section *** (PrepareDataObjectForEdit (DataObject) end)

            // *** End programmer edit section *** (PrepareDataObjectForEdit (DataObject) end)
        }
        
        protected override ICSSoft.STORMNET.UI.IEditor GetDpdForm()
        {
            // *** Start programmer edit section *** (MasterObjE.GetDpdForm() start)

            // *** End programmer edit section *** (MasterObjE.GetDpdForm() start)
            SimpleTestAuditProject.WinformMasterObjE form = new SimpleTestAuditProject.WinformMasterObjE();
            this.prv_AttachEventsFromDpdForm(form);
            return form;
        }
        
        public override Scriptizer.DataObjects.Script GetScript()
        {
            // *** Start programmer edit section *** (MasterObjE.GetScript start)

            // *** End programmer edit section *** (MasterObjE.GetScript start)
            Scriptizer.DataObjects.Script script = base.GetScript();
            // *** Start programmer edit section *** (MasterObjE.GetScript end)

            // *** End programmer edit section *** (MasterObjE.GetScript end)
            return script;
        }
        
        protected virtual void prv_AttachEventsFromDpdForm(object form)
        {
            // *** Start programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))

            // *** End programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))
            SimpleTestAuditProject.DPDIMasterObjE typedForm = ((SimpleTestAuditProject.DPDIMasterObjE)(form));
        }
    }
    
    /// <summary>
    /// Master obj E.
    /// </summary>
    // *** Start programmer edit section *** (DPDIMasterObjE CustomAttributes)

    // *** End programmer edit section *** (DPDIMasterObjE CustomAttributes)
    public interface DPDIMasterObjE
    {
        
        // *** Start programmer edit section *** (DPDIMasterObjE CustomMembers)

        // *** End programmer edit section *** (DPDIMasterObjE CustomMembers)

        // *** Start programmer edit section *** (DPDIMasterObjE Members)

        // *** End programmer edit section *** (DPDIMasterObjE Members)

    }
}
