//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using System.Drawing;
    using System.Collections;
    using System.ComponentModel;
    using System.Windows.Forms;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    // *** Start programmer edit section *** (WinformDetailMasterL CustomAttributes)

    // *** End programmer edit section *** (WinformDetailMasterL CustomAttributes)
    public class WinformDetailMasterL : ICSSoft.STORMNET.UI.BaseWinListStandard, SimpleTestAuditProject.DPDIDetailMasterL
    {
        
        // *** Start programmer edit section *** (Form Designer Fields)
        protected ICSSoft.STORMNET.Windows.Forms.AdvLimitComponent AdvLimit1;
        
        // *** End programmer edit section *** (Form Designer Fields)
        private System.ComponentModel.IContainer components = null;
        
        // *** Start programmer edit section *** (WinformDetailMasterL CustomMembers)

        // *** End programmer edit section *** (WinformDetailMasterL CustomMembers)

        
        public WinformDetailMasterL()
        {
            this.InitializeComponent();
            this.prv_TuneAdditionalObjectListViews();
            // *** Start programmer edit section *** (Form Constructor)

            // *** End programmer edit section *** (Form Constructor)
        }
        
        private void prv_TuneAdditionalObjectListViews()
        {
            // *** Start programmer edit section *** (prv_TuneAdditionalObjectListViews)

            // *** End programmer edit section *** (prv_TuneAdditionalObjectListViews)
        }
        
        // *** Start programmer edit section *** (Form Designer Initialize)
        private void InitializeComponent()
        {
            AdvLimit1 = new ICSSoft.STORMNET.Windows.Forms.AdvLimitComponent();

            // 
            // AdvLimit1
            // 
            AdvLimit1.CatchFormKeyEvents = true;
            AdvLimit1.ChangeCurrentLimitKeyCode = 131148;
            AdvLimit1.DiscardAllLimitsKeyCode = 131140;
            AdvLimit1.FilterSettingName = "";
            AdvLimit1.ObjectListView = objectListView1;
            AdvLimit1.OnToString = null;
            AdvLimit1.PermanentLimit = null;
            AdvLimit1.PublicateAccess = true;
            AdvLimit1.PublicateOperationId = -1;
            AdvLimit1.SecurityManager = null;
            AdvLimit1.ToolBarButtonIndex = 0;
            AdvLimit1.UserLimit = null;
            // 
            // objectListView1
            // 
            objectListView1.AdvansedColumns = null;
            objectListView1.AdvansedMarks = false;
            objectListView1.AllowSorting = true;
            objectListView1.AutoRefreshSupport = false;
            objectListView1.Columns = new ICSSoft.STORMNET.Windows.Forms.ColumnInfo[0];
            objectListView1.DataObjectTypes = new System.Type[] {
                    ((System.Type)(typeof(SimpleTestAuditProject.DetailMaster)))};
            objectListView1.Dock = System.Windows.Forms.DockStyle.Fill;
            objectListView1.DrawGrid = false;
            objectListView1.ExtendLastCol = true;
            objectListView1.FillDataOnLoad = true;
            objectListView1.FillDataOnLoadUserAllowed = true;
            objectListView1.GrayedOnLoad = true;
            objectListView1.HideToolBar = false;
            objectListView1.Limit = null;
            objectListView1.LoadingPackageSize = 500;
            objectListView1.Location = new System.Drawing.Point(0, 0);
            objectListView1.MemoryTimeLoadLimit = ((long)(200));
            objectListView1.Name = "objectListView1";
            objectListView1.Operations = ICSSoft.STORMNET.Windows.Forms.Operations.Parse("ShowMarks,Up,Search,SortTypeChanging,ColVisibleEdit,Preview,Print,Delete,New,Edit" +
                    ",Refresh,CopyDataToClipboard,PageSetup,NewByExample");
            objectListView1.RowCountQuery = 12345;
            objectListView1.ShowStatusBar = true;
            objectListView1.ShowToolTip = false;
            objectListView1.Size = new System.Drawing.Size(624, 365);
            objectListView1.Stylization = new ICSSoft.STORMNET.Windows.Forms.TextStylization("", new ICSSoft.STORMNET.Windows.Forms.TextStyle[0]);
            objectListView1.TabIndex = 0;
            objectListView1.UseAlternativeColoring = false;
            objectListView1.UseColumnOptimization = false;
            objectListView1.UseHotkeyForEdit = true;
            objectListView1.UseLimitFunctionExtension = false;
            objectListView1.UseToolBar = null;
            objectListView1.ViewName = "DetailMasterL";

            this.ClientSize = new System.Drawing.Size(624, 365);
            this.Controls.Add(objectListView1);
            this.IndpdListType = null;
            this.KeyPreview = true;
            this.ListControl = objectListView1;
            this.MinimumSize = new System.Drawing.Size(100, 100);
            this.Name = "UniWinListStandard";
            this.OutScreenControl = false;
            this.Text = "DetailMaster";
            this.Visible = false;
            this.VisiblePercent = 40;
        }
        
        // *** End programmer edit section *** (Form Designer Initialize)
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if ((components != null))
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }
    }
}
