//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using System.Drawing;
    using System.Collections;
    using System.ComponentModel;
    using System.Windows.Forms;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    // *** Start programmer edit section *** (WinformMasterObjE CustomAttributes)

    // *** End programmer edit section *** (WinformMasterObjE CustomAttributes)
    public class WinformMasterObjE : ICSSoft.STORMNET.UI.BaseWinEdit, SimpleTestAuditProject.DPDIMasterObjE
    {
        
        // *** Start programmer edit section *** (Form Designer Fields)
        protected System.Windows.Forms.TextBox ctrlMasterName;
        
        protected System.Windows.Forms.Label ctrlMasterNameLabel;
        
        protected System.Windows.Forms.TextBox ctrlMasterField;
        
        protected System.Windows.Forms.Label ctrlMasterFieldLabel;
        
        protected System.Windows.Forms.Panel EditPanel;
                protected ICSSoft.STORMNET.Windows.Forms.GroupEditBase MasterDetail;


        // *** End programmer edit section *** (Form Designer Fields)
        private System.ComponentModel.IContainer components = null;
        
        // *** Start programmer edit section *** (WinformMasterObjE CustomMembers)

        // *** End programmer edit section *** (WinformMasterObjE CustomMembers)

        
        public WinformMasterObjE()
        {
            this.InitializeComponent();
            m_sCaption = "Master obj E";
            this.prv_TuneLookupInformations();
            // *** Start programmer edit section *** (Form Constructor)

            // *** End programmer edit section *** (Form Constructor)
        }
        
        private void prv_TuneLookupInformations()
        {
            // *** Start programmer edit section *** (prv_TuneLookupInformations())

            // *** End programmer edit section *** (prv_TuneLookupInformations())
            m_arrGroupEditInformations.Add(new ICSSoft.STORMNET.UI.GroupEditInformation(this.MasterDetail, "MasterDetail", "STORMCASE.STORMNET.Generator.SerializeNewEditForm/EditPanel(Panel)/MasterDetail(G" +
                        "roupEditBase)"));
        }
        
        protected override void look_LookUpEvent(object sender, System.EventArgs e)
        {
            // *** Start programmer edit section *** (look_LookUpEvent( object sender, EventArgs e ))

            // *** End programmer edit section *** (look_LookUpEvent( object sender, EventArgs e ))
            base.look_LookUpEvent(sender, e);
        }
        
        protected override void gr_SetupEditorEventHandler(object sender, ICSSoft.STORMNET.Windows.Forms.SetupEditorEventArgs e)
        {
            // *** Start programmer edit section *** (gr_SetupEditorEventHandler( object sender, ICSSoft.STORMNET.Windows.Forms.SetupEditorEventArgs e ))

            // *** End programmer edit section *** (gr_SetupEditorEventHandler( object sender, ICSSoft.STORMNET.Windows.Forms.SetupEditorEventArgs e ))
            base.gr_SetupEditorEventHandler(sender, e);
            // *** Start programmer edit section *** (gr_SetupEditorEventHandler( object sender, ICSSoft.STORMNET.Windows.Forms.SetupEditorEventArgs e ) End)

            // *** End programmer edit section *** (gr_SetupEditorEventHandler( object sender, ICSSoft.STORMNET.Windows.Forms.SetupEditorEventArgs e ) End)
        }
        
        // *** Start programmer edit section *** (Form Designer Initialize)
        private void InitializeComponent()
        {
            ctrlMasterName = new System.Windows.Forms.TextBox();
            ctrlMasterNameLabel = new System.Windows.Forms.Label();
            ctrlMasterField = new System.Windows.Forms.TextBox();
            ctrlMasterFieldLabel = new System.Windows.Forms.Label();
            EditPanel = new System.Windows.Forms.Panel();

            MasterDetail = new ICSSoft.STORMNET.Windows.Forms.GroupEditBase();
            // 
            // MasterDetail
            // 
            MasterDetail.AdvansedMarks = false;
            MasterDetail.AllowRowLocking = false;
            MasterDetail.AlternativeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            MasterDetail.BackOnShiftEnter = false;
            MasterDetail.Bindings = new ICSSoft.STORMNET.Windows.Forms.Design.Binds("MasterDetailD", typeof(SimpleTestAuditProject.MasterDetail), new ICSSoft.STORMNET.Windows.Forms.Design.OneBind[0]);
            MasterDetail.Caption = "";
            MasterDetail.Columns = new ICSSoft.STORMNET.Windows.Forms.ColumnInfo[] {
        new ICSSoft.STORMNET.Windows.Forms.ColumnInfo("Field", 36, true, ICSSoft.STORMNET.Business.SortOrder.None, ((byte)(0)), "Field", false, false)};
            MasterDetail.DataObjectTypes = new System.Type[] {
        ((System.Type)(typeof(SimpleTestAuditProject.MasterDetail)))};
            MasterDetail.DataService = null;
            MasterDetail.DoNotAutoLoadItems = false;
            MasterDetail.EditManagerForMulipleEdit = null;
            MasterDetail.EditOnEnter = true;
            MasterDetail.EnableValueDisplayResponsibility = false;
            MasterDetail.GenerateValueChangedEventOnRowOperations = false;
            MasterDetail.KeepFocus = false;
            MasterDetail.LeaveOnLastEnter = false;
            MasterDetail.Location = new System.Drawing.Point(81, 64);
            MasterDetail.MoveNextOnEnter = false;
            MasterDetail.Name = "MasterDetail";
            MasterDetail.NewRowOnInsert = false;
            MasterDetail.NextOnEnter = false;
            MasterDetail.ObjectValue = null;
            MasterDetail.ReadOnly = false;
            MasterDetail.ShowAutoResizeBtn = true;
            MasterDetail.ShowCopyBtn = true;
            MasterDetail.ShowCopyCSVBtn = true;
            MasterDetail.ShowDeleteButton = true;
            MasterDetail.ShowDeleted = false;
            MasterDetail.ShowDnBtn = false;
            MasterDetail.ShowMarkBySelectionBtn = false;
            MasterDetail.ShowMarks = true;
            MasterDetail.ShowNewBtn = true;
            MasterDetail.ShowPasteBtn = true;
            MasterDetail.ShowPreviewBtn = true;
            MasterDetail.ShowPrintBtn = true;
            MasterDetail.ShowPrintSettingsBtn = true;
            MasterDetail.ShowShowDeletedRows = true;
            MasterDetail.ShowStatusBar = false;
            MasterDetail.ShowUpBtn = false;
            MasterDetail.ShowVisibleColumnsButton = true;
            MasterDetail.Size = new System.Drawing.Size(736, 220);
            MasterDetail.Stylization = new ICSSoft.STORMNET.Windows.Forms.TextStylization("", new ICSSoft.STORMNET.Windows.Forms.TextStyle[0]);
            MasterDetail.TabIndex = 4;
            MasterDetail.UseAlternativeColoring = true;
            MasterDetail.ViewName = "MasterDetailD";

            // 
            // ctrlMasterName
            // 
            ctrlMasterName.Location = new System.Drawing.Point(81, 12);
            ctrlMasterName.MaxLength = 255;
            ctrlMasterName.Name = "ctrlMasterName";
            ctrlMasterName.TabIndex = 0;
            // 
            // ctrlMasterNameLabel
            // 
            ctrlMasterNameLabel.AutoSize = true;
            ctrlMasterNameLabel.Location = new System.Drawing.Point(11, 16);
            ctrlMasterNameLabel.Name = "ctrlMasterNameLabel";
            ctrlMasterNameLabel.Size = new System.Drawing.Size(69, 17);
            ctrlMasterNameLabel.TabIndex = 1;
            ctrlMasterNameLabel.Text = "MasterName";
            ctrlMasterNameLabel.UseCompatibleTextRendering = true;
            // 
            // ctrlMasterField
            // 
            ctrlMasterField.Location = new System.Drawing.Point(81, 38);
            ctrlMasterField.Name = "ctrlMasterField";
            ctrlMasterField.TabIndex = 2;
            // 
            // ctrlMasterFieldLabel
            // 
            ctrlMasterFieldLabel.AutoSize = true;
            ctrlMasterFieldLabel.Location = new System.Drawing.Point(15, 42);
            ctrlMasterFieldLabel.Name = "ctrlMasterFieldLabel";
            ctrlMasterFieldLabel.Size = new System.Drawing.Size(63, 17);
            ctrlMasterFieldLabel.TabIndex = 3;
            ctrlMasterFieldLabel.Text = "MasterField";
            ctrlMasterFieldLabel.UseCompatibleTextRendering = true;
            // 
            // EditPanel
            // 
            EditPanel.AutoScroll = true;
            EditPanel.AutoScrollMinSize = new System.Drawing.Size(187, 64);
            EditPanel.BackColor = System.Drawing.SystemColors.Control;
            EditPanel.Controls.Add(ctrlMasterName);
            EditPanel.Controls.Add(ctrlMasterNameLabel);
            EditPanel.Controls.Add(ctrlMasterField);
            EditPanel.Controls.Add(ctrlMasterFieldLabel);
            EditPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            EditPanel.Location = new System.Drawing.Point(0, 42);
            EditPanel.Name = "EditPanel";
            EditPanel.Size = new System.Drawing.Size(187, 64);
            EditPanel.TabIndex = 2;
            // 
            this.EditPanel.Controls.Add(this.MasterDetail);
            // EditManager
            // 
            EditManager.Bindings = new ICSSoft.STORMNET.Windows.Forms.Design.Binds("MasterObjE", typeof(SimpleTestAuditProject.MasterObj), new ICSSoft.STORMNET.Windows.Forms.Design.OneBind[] {new ICSSoft.STORMNET.Windows.Forms.Design.OneBind(ctrlMasterField, typeof(System.Windows.Forms.TextBox), "Text", new System.Type[] {
                                    ((System.Type)(typeof(int))),
                                    ((System.Type)(typeof(string)))}, "MasterField"),
                        new ICSSoft.STORMNET.Windows.Forms.Design.OneBind(ctrlMasterName, typeof(System.Windows.Forms.TextBox), "Text", null, "MasterName"), new ICSSoft.STORMNET.Windows.Forms.Design.OneBind(MasterDetail, typeof(ICSSoft.STORMNET.Windows.Forms.GroupEditBase), "Value", null, "MasterDetail")});
            EditManager.NotNullToolTip = "Необходимо заполнить";
            EditManager.ReadOnly = false;
            // 
            // Save
            // 
            Save.ImageIndex = 0;
            Save.Name = "Save";
            Save.Tag = "Save";
            Save.ToolTipText = "Сохранить документ (Ctrl+S)";
            // 
            // SaveAndClose
            // 
            SaveAndClose.ImageIndex = 1;
            SaveAndClose.Name = "SaveAndClose";
            SaveAndClose.Tag = "SaveAndClose";
            SaveAndClose.ToolTipText = "Сохранить и закрыть (Ctrl+Q)";
            // 
            // PrintButton
            // 
            PrintButton.ImageIndex = 2;
            PrintButton.Name = "PrintButton";
            PrintButton.Tag = "Print";
            PrintButton.ToolTipText = "Печать";
            PrintButton.Visible = false;
            // 
            // PreviewButton
            // 
            PreviewButton.ImageIndex = 3;
            PreviewButton.Name = "PreviewButton";
            PreviewButton.Tag = "Preview";
            PreviewButton.ToolTipText = "Предварительный просмотр (Ctrl+P)";
            PreviewButton.Visible = false;

            this.AutoScroll = true;
            this.Caption = "Master obj E";
            this.ClientSize = new System.Drawing.Size(187, 126);
            this.ContPath = "";
            this.Controls.Add(EditPanel);
            this.DataObject = null;
            this.KeyPreview = true;
            this.Name = "UniWinEdit";
            this.OutScreenControl = false;
            this.PromtUserForActionAtCloseText = "Сохранить документ?";
            this.PropertyName = "";
            this.Text = "UniWinEdit";
            this.Visible = false;
            this.VisiblePercent = 40;
            this.Controls.SetChildIndex(this.EditPanel, 0);
        }
        
        // *** End programmer edit section *** (Form Designer Initialize)
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if ((components != null))
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }
    }
}
