//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.GosUslugi
{
    using System;


    // *** Start programmer edit section *** (Using statements)
    using System.Collections.Generic;
    using Iis.Eais.Common.Errors;
    using Iis.Eais.GosUslugi.Helpers;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SpecialistBS.
    /// </summary>
    // *** Start programmer edit section *** (SpecialistBS CustomAttributes)

    // *** End programmer edit section *** (SpecialistBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class SpecialistBS : Iis.Eais.Common.CommonBS
    {

        // *** Start programmer edit section *** (SpecialistBS CustomMembers)
        public override List<IError> CanDelete(Type type, Guid objectId)
        {
            List<IError> errors = new List<IError>();

            // Проверка связанных объектов по списку
            errors.AddRange(CheckRelationsBeforDelete(objectId, RelationsToCheckBeforeDelete.Specialist));

            return errors;
        }
        // *** End programmer edit section *** (SpecialistBS CustomMembers)

        // *** Start programmer edit section *** (OnUpdateSpecialist CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSpecialist CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSpecialist(Iis.Eais.GosUslugi.Specialist UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSpecialist)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateSpecialist)
        }
    }
}
