//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;


    // *** Start programmer edit section *** (Using statements)
    using System.Collections.Generic;
    using Iis.Eais.Common.Errors;
    using Iis.Eais.Catalogs.Helpers;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// StatiaAktaBS.
    /// </summary>
    // *** Start programmer edit section *** (StatiaAktaBS CustomAttributes)

    // *** End programmer edit section *** (StatiaAktaBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class StatiaAktaBS : Iis.Eais.Common.CommonBS
    {

        // *** Start programmer edit section *** (StatiaAktaBS CustomMembers)
        public override List<IError> CanDelete(Type type, Guid objectId)
        {
            List<IError> errors = new List<IError>();

            // Проверка связанных объектов по списку
            errors.AddRange(CheckRelationsBeforDelete(objectId, RelationsToCheckBeforeDelete.StatiaAkta));

            return errors;
        }
        // *** End programmer edit section *** (StatiaAktaBS CustomMembers)


        // *** Start programmer edit section *** (OnUpdateStatiaAkta CustomAttributes)

        // *** End programmer edit section *** (OnUpdateStatiaAkta CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateStatiaAkta(Iis.Eais.Catalogs.StatiaAkta UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateStatiaAkta)
            UpdatedObject.Oldid = new CatalogsBS().MakeIdIfEmpty(UpdatedObject);

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateStatiaAkta)
        }
    }
}
