//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synchronization.Objects
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Source.
    /// </summary>
    // *** Start programmer edit section *** (Source CustomAttributes)

    // *** End programmer edit section *** (Source CustomAttributes)
    [AutoAltered()]
    [Caption("Источник данных")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("SourceE", new string[] {
            "name",
            "id"})]
    public class Source : ICSSoft.STORMNET.DataObject
    {

        private string fname;

        private string fid;

        // *** Start programmer edit section *** (Source CustomMembers)

        // *** End programmer edit section *** (Source CustomMembers)


        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (Source.name CustomAttributes)

        // *** End programmer edit section *** (Source.name CustomAttributes)
        [StrLen(255)]
        [NotNull]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (Source.name Get start)

                // *** End programmer edit section *** (Source.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (Source.name Get end)

                // *** End programmer edit section *** (Source.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Source.name Set start)

                // *** End programmer edit section *** (Source.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (Source.name Set end)

                // *** End programmer edit section *** (Source.name Set end)
            }
        }

        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (Source.id CustomAttributes)

        // *** End programmer edit section *** (Source.id CustomAttributes)
        [StrLen(7)]
        public virtual string id
        {
            get
            {
                // *** Start programmer edit section *** (Source.id Get start)

                // *** End programmer edit section *** (Source.id Get start)
                string result = this.fid;
                // *** Start programmer edit section *** (Source.id Get end)

                // *** End programmer edit section *** (Source.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Source.id Set start)

                // *** End programmer edit section *** (Source.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (Source.id Set end)

                // *** End programmer edit section *** (Source.id Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "SourceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SourceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SourceE", typeof(Synchronization.Objects.Source));
                }
            }
        }
    }
}
