//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Leechnost
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T Логический.
    /// </summary>
    // *** Start programmer edit section *** (tLogicheskii CustomAttributes)

    // *** End programmer edit section *** (tLogicheskii CustomAttributes)
    public enum tLogicheskii
    {

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tLogicheskii.Pusto CustomAttributes)

        // *** End programmer edit section *** (tLogicheskii.Pusto CustomAttributes)
        [Caption("")]
        Pusto,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tLogicheskii.Net CustomAttributes)

        // *** End programmer edit section *** (tLogicheskii.Net CustomAttributes)
        [Caption("Нет")]
        Net,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tLogicheskii.Da CustomAttributes)

        // *** End programmer edit section *** (tLogicheskii.Da CustomAttributes)
        [Caption("Да")]
        Da,
    }
}
