//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Leechnost
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// t Образование личности.
    /// </summary>
    // *** Start programmer edit section *** (tObrazovanieLeechn CustomAttributes)

    // *** End programmer edit section *** (tObrazovanieLeechn CustomAttributes)
    public enum tObrazovanieLeechn
    {

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tObrazovanieLeechn.Pusto CustomAttributes)

        // *** End programmer edit section *** (tObrazovanieLeechn.Pusto CustomAttributes)
        [Caption("")]
        Pusto,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tObrazovanieLeechn.Obshchee CustomAttributes)

        // *** End programmer edit section *** (tObrazovanieLeechn.Obshchee CustomAttributes)
        [Caption("Общее")]
        Obshchee,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tObrazovanieLeechn.SredneeProf CustomAttributes)

        // *** End programmer edit section *** (tObrazovanieLeechn.SredneeProf CustomAttributes)
        [Caption("Среднее профессиональное")]
        SredneeProf,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tObrazovanieLeechn.Vysshee CustomAttributes)

        // *** End programmer edit section *** (tObrazovanieLeechn.Vysshee CustomAttributes)
        [Caption("Высшее")]
        Vysshee,
    }
}
