//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Leechnost
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// t Тип адреса.
    /// </summary>
    // *** Start programmer edit section *** (tTipAdresa CustomAttributes)

    // *** End programmer edit section *** (tTipAdresa CustomAttributes)
    public enum tTipAdresa
    {

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tTipAdresa.Pusto CustomAttributes)

        // *** End programmer edit section *** (tTipAdresa.Pusto CustomAttributes)
        [Caption("")]
        Pusto,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tTipAdresa.Propiska CustomAttributes)

        // *** End programmer edit section *** (tTipAdresa.Propiska CustomAttributes)
        [Caption("Прописка")]
        Propiska,

        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tTipAdresa.Prozhivanie CustomAttributes)

        // *** End programmer edit section *** (tTipAdresa.Prozhivanie CustomAttributes)
        [Caption("Проживание")]
        Prozhivanie,
    }
}
