//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;


    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перечень справочников.
    /// </summary>
    // *** Start programmer edit section *** (Catalog CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (Catalog CustomAttributes)
    [BusinessServer("Iis.Eais.Catalogs.CatalogBS, Eais.Catalogs.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Перечень справочников")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Code as \'Код\'",
            "Name as \'Имя\'",
            "Description as \'Описание\'"})]
    [AssociatedDetailViewAttribute("AuditView", "Values", "ForeignCatValueE", true, "", "Values", true, new string[] {
            ""})]
    [View("CatalogE", new string[] {
            "Code as \'Код\'",
            "Name as \'Имя\'",
            "Description as \'Описание\'",
            "CreateTime"}, Hidden = new string[] {
            "CreateTime"})]
    [AssociatedDetailViewAttribute("CatalogE", "Values", "ForeignCatValueE", true, "", "", false, new string[] {
            ""})]
    [View("CatalogL", new string[] {
            "Code as \'Код\'",
            "Name as \'Имя\'",
            "Description as \'Описание\'",
            "CreateTime as \'Время создания\'",
            "Creator as \'Создатель\'",
            "EditTime as \'Время последнего редактирования\'",
            "Editor as \'Последний редактор\'"})]
    public class Catalog : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {

        private string fCode;

        private string fName;

        private string fDescription;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        private Iis.Eais.Catalogs.DetailArrayOfForeignCatValue fValues;

        // *** Start programmer edit section *** (Catalog CustomMembers)

        // *** End programmer edit section *** (Catalog CustomMembers)


        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Code CustomAttributes)

        // *** End programmer edit section *** (Catalog.Code CustomAttributes)
        public virtual string Code
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Code Get start)

                // *** End programmer edit section *** (Catalog.Code Get start)
                string result = this.fCode;
                // *** Start programmer edit section *** (Catalog.Code Get end)

                // *** End programmer edit section *** (Catalog.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Code Set start)

                // *** End programmer edit section *** (Catalog.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (Catalog.Code Set end)

                // *** End programmer edit section *** (Catalog.Code Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Name CustomAttributes)

        // *** End programmer edit section *** (Catalog.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Name Get start)

                // *** End programmer edit section *** (Catalog.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Catalog.Name Get end)

                // *** End programmer edit section *** (Catalog.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Name Set start)

                // *** End programmer edit section *** (Catalog.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Catalog.Name Set end)

                // *** End programmer edit section *** (Catalog.Name Set end)
            }
        }

        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Description CustomAttributes)

        // *** End programmer edit section *** (Catalog.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Description Get start)

                // *** End programmer edit section *** (Catalog.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Catalog.Description Get end)

                // *** End programmer edit section *** (Catalog.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Description Set start)

                // *** End programmer edit section *** (Catalog.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Catalog.Description Set end)

                // *** End programmer edit section *** (Catalog.Description Set end)
            }
        }

        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Catalog.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.CreateTime Get start)

                // *** End programmer edit section *** (Catalog.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Catalog.CreateTime Get end)

                // *** End programmer edit section *** (Catalog.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.CreateTime Set start)

                // *** End programmer edit section *** (Catalog.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Catalog.CreateTime Set end)

                // *** End programmer edit section *** (Catalog.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Creator CustomAttributes)

        // *** End programmer edit section *** (Catalog.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Creator Get start)

                // *** End programmer edit section *** (Catalog.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Catalog.Creator Get end)

                // *** End programmer edit section *** (Catalog.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Creator Set start)

                // *** End programmer edit section *** (Catalog.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Catalog.Creator Set end)

                // *** End programmer edit section *** (Catalog.Creator Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.EditTime CustomAttributes)

        // *** End programmer edit section *** (Catalog.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.EditTime Get start)

                // *** End programmer edit section *** (Catalog.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Catalog.EditTime Get end)

                // *** End programmer edit section *** (Catalog.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.EditTime Set start)

                // *** End programmer edit section *** (Catalog.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Catalog.EditTime Set end)

                // *** End programmer edit section *** (Catalog.EditTime Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Editor CustomAttributes)

        // *** End programmer edit section *** (Catalog.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Editor Get start)

                // *** End programmer edit section *** (Catalog.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Catalog.Editor Get end)

                // *** End programmer edit section *** (Catalog.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Editor Set start)

                // *** End programmer edit section *** (Catalog.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Catalog.Editor Set end)

                // *** End programmer edit section *** (Catalog.Editor Set end)
            }
        }

        /// <summary>
        /// Перечень справочников.
        /// </summary>
        // *** Start programmer edit section *** (Catalog.Values CustomAttributes)

        // *** End programmer edit section *** (Catalog.Values CustomAttributes)
        public virtual Iis.Eais.Catalogs.DetailArrayOfForeignCatValue Values
        {
            get
            {
                // *** Start programmer edit section *** (Catalog.Values Get start)

                // *** End programmer edit section *** (Catalog.Values Get start)
                if ((this.fValues == null))
                {
                    this.fValues = new Iis.Eais.Catalogs.DetailArrayOfForeignCatValue(this);
                }
                Iis.Eais.Catalogs.DetailArrayOfForeignCatValue result = this.fValues;
                // *** Start programmer edit section *** (Catalog.Values Get end)

                // *** End programmer edit section *** (Catalog.Values Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Catalog.Values Set start)

                // *** End programmer edit section *** (Catalog.Values Set start)
                this.fValues = value;
                // *** Start programmer edit section *** (Catalog.Values Set end)

                // *** End programmer edit section *** (Catalog.Values Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.Catalogs.Catalog));
                }
            }

            /// <summary>
            /// "CatalogE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogE", typeof(Iis.Eais.Catalogs.Catalog));
                }
            }

            /// <summary>
            /// "CatalogL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CatalogL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CatalogL", typeof(Iis.Eais.Catalogs.Catalog));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
