//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;


    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ForeignCatValue.
    /// </summary>
    // *** Start programmer edit section *** (ForeignCatValue CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (ForeignCatValue CustomAttributes)
    [BusinessServer("Iis.Eais.Catalogs.ForeignCatValueBS, Eais.Catalogs.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "SysCode as \'SysCode\'",
            "Code as \'Code\'",
            "Description as \'Description\'",
            "NoActual as \'NoActual\'",
            "FullValue as \'FullValue\'",
            "Catalog as \'Catalog\'",
            "ParentGuid as \'ParentGuid\'"})]
    [View("ForeignCatValueE", new string[] {
            "SysCode as \'Служебный код\'",
            "Code as \'Код\'",
            "Description as \'Описание\'",
            "NoActual as \'Не актуален с\'",
            "FullValue as \'Значение\'",
            "ParentGuid",
            "ParentGuid.Code",
            "ParentDescription as \'Описание\'",
            "Catalog"}, Hidden = new string[] {
            "ParentGuid",
            "ParentGuid.Code",
            "Catalog"})]
    [View("ForeignCatValueL", new string[] {
            "SysCode as \'Служебный код\'",
            "Code as \'Код\'",
            "Description as \'Описание\'",
            "ParentDescription as \'Описание\'",
            "NoActual as \'Не актуален с\'",
            "FullValue as \'Содержимое\'",
            "CreateTime as \'Время создания\'",
            "Creator as \'Создатель\'",
            "EditTime as \'Время последнего редактирования\'",
            "Editor as \'Последний редактор\'",
            "Catalog"}, Hidden = new string[] {
            "Catalog"})]
    public class ForeignCatValue : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {

        private string fSysCode;

        private string fCode;

        private string fDescription;

        private System.DateTime? fNoActual;

        private string fFullValue;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        private Iis.Eais.Catalogs.ForeignCatValue fParentGuid;

        private Iis.Eais.Catalogs.Catalog fCatalog;

        // *** Start programmer edit section *** (ForeignCatValue CustomMembers)

        // *** End programmer edit section *** (ForeignCatValue CustomMembers)


        /// <summary>
        /// SysCode.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.SysCode CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.SysCode CustomAttributes)
        public virtual string SysCode
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.SysCode Get start)

                // *** End programmer edit section *** (ForeignCatValue.SysCode Get start)
                string result = this.fSysCode;
                // *** Start programmer edit section *** (ForeignCatValue.SysCode Get end)

                // *** End programmer edit section *** (ForeignCatValue.SysCode Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.SysCode Set start)

                // *** End programmer edit section *** (ForeignCatValue.SysCode Set start)
                this.fSysCode = value;
                // *** Start programmer edit section *** (ForeignCatValue.SysCode Set end)

                // *** End programmer edit section *** (ForeignCatValue.SysCode Set end)
            }
        }

        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.Code CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.Code CustomAttributes)
        public virtual string Code
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.Code Get start)

                // *** End programmer edit section *** (ForeignCatValue.Code Get start)
                string result = this.fCode;
                // *** Start programmer edit section *** (ForeignCatValue.Code Get end)

                // *** End programmer edit section *** (ForeignCatValue.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.Code Set start)

                // *** End programmer edit section *** (ForeignCatValue.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (ForeignCatValue.Code Set end)

                // *** End programmer edit section *** (ForeignCatValue.Code Set end)
            }
        }

        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.Description CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.Description Get start)

                // *** End programmer edit section *** (ForeignCatValue.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (ForeignCatValue.Description Get end)

                // *** End programmer edit section *** (ForeignCatValue.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.Description Set start)

                // *** End programmer edit section *** (ForeignCatValue.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (ForeignCatValue.Description Set end)

                // *** End programmer edit section *** (ForeignCatValue.Description Set end)
            }
        }

        /// <summary>
        /// ParentDescription.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.ParentDescription CustomAttributes)
        private string cashedParentDescription = null;
        // *** End programmer edit section *** (ForeignCatValue.ParentDescription CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "recursive_function (\'\', STORMMainObjectKey)")]
        public virtual string ParentDescription
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.ParentDescription Get)
                return this.cashedParentDescription;
                // *** End programmer edit section *** (ForeignCatValue.ParentDescription Get)
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.ParentDescription Set)
                if (value != null)
                {
                    this.cashedParentDescription = value;
                }
                // *** End programmer edit section *** (ForeignCatValue.ParentDescription Set)
            }
        }

        /// <summary>
        /// NoActual.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.NoActual CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.NoActual CustomAttributes)
        public virtual System.DateTime? NoActual
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.NoActual Get start)

                // *** End programmer edit section *** (ForeignCatValue.NoActual Get start)
                System.DateTime? result = this.fNoActual;
                // *** Start programmer edit section *** (ForeignCatValue.NoActual Get end)

                // *** End programmer edit section *** (ForeignCatValue.NoActual Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.NoActual Set start)

                // *** End programmer edit section *** (ForeignCatValue.NoActual Set start)
                this.fNoActual = value;
                // *** Start programmer edit section *** (ForeignCatValue.NoActual Set end)

                // *** End programmer edit section *** (ForeignCatValue.NoActual Set end)
            }
        }

        /// <summary>
        /// FullValue.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.FullValue CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.FullValue CustomAttributes)
        public virtual string FullValue
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.FullValue Get start)

                // *** End programmer edit section *** (ForeignCatValue.FullValue Get start)
                string result = this.fFullValue;
                // *** Start programmer edit section *** (ForeignCatValue.FullValue Get end)

                // *** End programmer edit section *** (ForeignCatValue.FullValue Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.FullValue Set start)

                // *** End programmer edit section *** (ForeignCatValue.FullValue Set start)
                this.fFullValue = value;
                // *** Start programmer edit section *** (ForeignCatValue.FullValue Set end)

                // *** End programmer edit section *** (ForeignCatValue.FullValue Set end)
            }
        }

        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.CreateTime Get start)

                // *** End programmer edit section *** (ForeignCatValue.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ForeignCatValue.CreateTime Get end)

                // *** End programmer edit section *** (ForeignCatValue.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.CreateTime Set start)

                // *** End programmer edit section *** (ForeignCatValue.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ForeignCatValue.CreateTime Set end)

                // *** End programmer edit section *** (ForeignCatValue.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.Creator CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.Creator Get start)

                // *** End programmer edit section *** (ForeignCatValue.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ForeignCatValue.Creator Get end)

                // *** End programmer edit section *** (ForeignCatValue.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.Creator Set start)

                // *** End programmer edit section *** (ForeignCatValue.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ForeignCatValue.Creator Set end)

                // *** End programmer edit section *** (ForeignCatValue.Creator Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.EditTime CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.EditTime Get start)

                // *** End programmer edit section *** (ForeignCatValue.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ForeignCatValue.EditTime Get end)

                // *** End programmer edit section *** (ForeignCatValue.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.EditTime Set start)

                // *** End programmer edit section *** (ForeignCatValue.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ForeignCatValue.EditTime Set end)

                // *** End programmer edit section *** (ForeignCatValue.EditTime Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.Editor CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.Editor Get start)

                // *** End programmer edit section *** (ForeignCatValue.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ForeignCatValue.Editor Get end)

                // *** End programmer edit section *** (ForeignCatValue.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.Editor Set start)

                // *** End programmer edit section *** (ForeignCatValue.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ForeignCatValue.Editor Set end)

                // *** End programmer edit section *** (ForeignCatValue.Editor Set end)
            }
        }

        /// <summary>
        /// ForeignCatValue.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.ParentGuid CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.ParentGuid CustomAttributes)
        [PropertyStorage(new string[] {
                "ParentGuid"})]
        public virtual Iis.Eais.Catalogs.ForeignCatValue ParentGuid
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.ParentGuid Get start)

                // *** End programmer edit section *** (ForeignCatValue.ParentGuid Get start)
                Iis.Eais.Catalogs.ForeignCatValue result = this.fParentGuid;
                // *** Start programmer edit section *** (ForeignCatValue.ParentGuid Get end)

                // *** End programmer edit section *** (ForeignCatValue.ParentGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.ParentGuid Set start)

                // *** End programmer edit section *** (ForeignCatValue.ParentGuid Set start)
                this.fParentGuid = value;
                // *** Start programmer edit section *** (ForeignCatValue.ParentGuid Set end)

                // *** End programmer edit section *** (ForeignCatValue.ParentGuid Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку Iis.Eais.Catalogs.Catalog.
        /// </summary>
        // *** Start programmer edit section *** (ForeignCatValue.Catalog CustomAttributes)

        // *** End programmer edit section *** (ForeignCatValue.Catalog CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Catalog"})]
        public virtual Iis.Eais.Catalogs.Catalog Catalog
        {
            get
            {
                // *** Start programmer edit section *** (ForeignCatValue.Catalog Get start)

                // *** End programmer edit section *** (ForeignCatValue.Catalog Get start)
                Iis.Eais.Catalogs.Catalog result = this.fCatalog;
                // *** Start programmer edit section *** (ForeignCatValue.Catalog Get end)

                // *** End programmer edit section *** (ForeignCatValue.Catalog Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ForeignCatValue.Catalog Set start)

                // *** End programmer edit section *** (ForeignCatValue.Catalog Set start)
                this.fCatalog = value;
                // *** Start programmer edit section *** (ForeignCatValue.Catalog Set end)

                // *** End programmer edit section *** (ForeignCatValue.Catalog Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.Catalogs.ForeignCatValue));
                }
            }

            /// <summary>
            /// "ForeignCatValueE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ForeignCatValueE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ForeignCatValueE", typeof(Iis.Eais.Catalogs.ForeignCatValue));
                }
            }

            /// <summary>
            /// "ForeignCatValueL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ForeignCatValueL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ForeignCatValueL", typeof(Iis.Eais.Catalogs.ForeignCatValue));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }

    /// <summary>
    /// Detail array of ForeignCatValue.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfForeignCatValue CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (DetailArrayDetailArrayOfForeignCatValue CustomAttributes)
    public class DetailArrayOfForeignCatValue : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (Iis.Eais.Catalogs.DetailArrayOfForeignCatValue members)

        // *** End programmer edit section *** (Iis.Eais.Catalogs.DetailArrayOfForeignCatValue members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ForeignCatValue by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ForeignCatValue.
        /// </summary>
        public DetailArrayOfForeignCatValue(Iis.Eais.Catalogs.Catalog fCatalog) :
                base(typeof(ForeignCatValue), ((ICSSoft.STORMNET.DataObject)(fCatalog)))
        {
        }

        public Iis.Eais.Catalogs.ForeignCatValue this[int index]
        {
            get
            {
                return ((Iis.Eais.Catalogs.ForeignCatValue)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(Iis.Eais.Catalogs.ForeignCatValue dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
