//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;


    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;

    using IIS.Synchronizer;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Льгота для категории.
    /// </summary>
    // *** Start programmer edit section *** (LgotaDliaKat CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (LgotaDliaKat CustomAttributes)
    [BusinessServer("Iis.Eais.Catalogs.CatalogsBS, Eais.Catalogs.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Льгота для категории")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "DataNaznacheniia as \'Дата назначения\'",
            "PeriodPredost as \'Период предоставления\'",
            "TipVyplaty as \'Тип выплаты\'",
            "DataOtmeny as \'Дата отмены\'",
            "Lgota as \'Льгота\'",
            "Lgota.Tip.Naimenovanie as \'Тип льготы\'",
            "Lgota.VclVSotcPaket as \'Вкл. в соцпакет\'",
            "Osnovanie as \'№ статьи\'",
            "IstochnikFin as \'Источник финансирования\'",
            "Kategoriia as \'Категория\'",
            "Oldid as \'Ид\'"})]
    [View("LgotaDliaKat", new string[] {
            "DataNaznacheniia as \'Дата назначения\'",
            "PeriodPredost as \'Период предоставления\'",
            "TipVyplaty as \'Тип выплаты\'",
            "DataOtmeny as \'Дата отмены\'",
            "Lgota as \'Льгота\'",
            "Lgota.Tip.Naimenovanie as \'Тип льготы\'",
            "Lgota.VclVSotcPaket as \'Вкл. в соцпакет\'",
            "Osnovanie as \'№ статьи\'",
            "IstochnikFin as \'Источник финансирования\'",
            "Oldid as \'Ид\'"})]
    [MasterViewDefineAttribute("LgotaDliaKat", "Osnovanie", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Nomer")]
    [View("LgotaDliaKatE", new string[] {
            "Lgota as \'Льгота\'",
            "Lgota.Naimenovanie",
            "Osnovanie as \'№ статьи\'",
            "Osnovanie.Nomer",
            "IstochnikFin as \'Источник финансирования\'",
            "IstochnikFin.Naimenovanie",
            "DataNaznacheniia as \'Дата назначения\'",
            "DataOtmeny as \'Дата отмены\'",
            "PeriodPredost as \'Период предоставления\'",
            "TipVyplaty as \'Тип выплаты\'",
            "Oldid as \'Ид\'"}, Hidden = new string[] {
            "Lgota.Naimenovanie",
            "Osnovanie.Nomer",
            "IstochnikFin.Naimenovanie"})]
    [MasterViewDefineAttribute("LgotaDliaKatE", "Lgota", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Naimenovanie")]
    [MasterViewDefineAttribute("LgotaDliaKatE", "Osnovanie", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Nomer")]
    [MasterViewDefineAttribute("LgotaDliaKatE", "IstochnikFin", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Naimenovanie")]
    public class LgotaDliaKat : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields, ISync
    {

        private System.DateTime? fDataNaznacheniia;

        private System.DateTime? fDataOtmeny;

        private Iis.Eais.Catalogs.tTipPerioda fPeriodPredost;

        private Iis.Eais.Catalogs.tTipVyplaty fTipVyplaty;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        private int fOldid;

        private Iis.Eais.Catalogs.StatiaAkta fOsnovanie;

        private Iis.Eais.Catalogs.Lgota fLgota;

        private Iis.Eais.Catalogs.IstochnikFin fIstochnikFin;

        private Iis.Eais.Catalogs.LgotKat fKategoriia;

        // *** Start programmer edit section *** (LgotaDliaKat CustomMembers)

        // *** End programmer edit section *** (LgotaDliaKat CustomMembers)


        /// <summary>
        /// DataNaznacheniia.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.DataNaznacheniia CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.DataNaznacheniia CustomAttributes)
        public virtual System.DateTime? DataNaznacheniia
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.DataNaznacheniia Get start)

                // *** End programmer edit section *** (LgotaDliaKat.DataNaznacheniia Get start)
                System.DateTime? result = this.fDataNaznacheniia;
                // *** Start programmer edit section *** (LgotaDliaKat.DataNaznacheniia Get end)

                // *** End programmer edit section *** (LgotaDliaKat.DataNaznacheniia Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.DataNaznacheniia Set start)

                // *** End programmer edit section *** (LgotaDliaKat.DataNaznacheniia Set start)
                this.fDataNaznacheniia = value;
                // *** Start programmer edit section *** (LgotaDliaKat.DataNaznacheniia Set end)

                // *** End programmer edit section *** (LgotaDliaKat.DataNaznacheniia Set end)
            }
        }

        /// <summary>
        /// DataOtmeny.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.DataOtmeny CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.DataOtmeny CustomAttributes)
        public virtual System.DateTime? DataOtmeny
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.DataOtmeny Get start)

                // *** End programmer edit section *** (LgotaDliaKat.DataOtmeny Get start)
                System.DateTime? result = this.fDataOtmeny;
                // *** Start programmer edit section *** (LgotaDliaKat.DataOtmeny Get end)

                // *** End programmer edit section *** (LgotaDliaKat.DataOtmeny Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.DataOtmeny Set start)

                // *** End programmer edit section *** (LgotaDliaKat.DataOtmeny Set start)
                this.fDataOtmeny = value;
                // *** Start programmer edit section *** (LgotaDliaKat.DataOtmeny Set end)

                // *** End programmer edit section *** (LgotaDliaKat.DataOtmeny Set end)
            }
        }

        /// <summary>
        /// PeriodPredost.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.PeriodPredost CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.PeriodPredost CustomAttributes)
        public virtual Iis.Eais.Catalogs.tTipPerioda PeriodPredost
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.PeriodPredost Get start)

                // *** End programmer edit section *** (LgotaDliaKat.PeriodPredost Get start)
                Iis.Eais.Catalogs.tTipPerioda result = this.fPeriodPredost;
                // *** Start programmer edit section *** (LgotaDliaKat.PeriodPredost Get end)

                // *** End programmer edit section *** (LgotaDliaKat.PeriodPredost Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.PeriodPredost Set start)

                // *** End programmer edit section *** (LgotaDliaKat.PeriodPredost Set start)
                this.fPeriodPredost = value;
                // *** Start programmer edit section *** (LgotaDliaKat.PeriodPredost Set end)

                // *** End programmer edit section *** (LgotaDliaKat.PeriodPredost Set end)
            }
        }

        /// <summary>
        /// TipVyplaty.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.TipVyplaty CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.TipVyplaty CustomAttributes)
        public virtual Iis.Eais.Catalogs.tTipVyplaty TipVyplaty
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.TipVyplaty Get start)

                // *** End programmer edit section *** (LgotaDliaKat.TipVyplaty Get start)
                Iis.Eais.Catalogs.tTipVyplaty result = this.fTipVyplaty;
                // *** Start programmer edit section *** (LgotaDliaKat.TipVyplaty Get end)

                // *** End programmer edit section *** (LgotaDliaKat.TipVyplaty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.TipVyplaty Set start)

                // *** End programmer edit section *** (LgotaDliaKat.TipVyplaty Set start)
                this.fTipVyplaty = value;
                // *** Start programmer edit section *** (LgotaDliaKat.TipVyplaty Set end)

                // *** End programmer edit section *** (LgotaDliaKat.TipVyplaty Set end)
            }
        }

        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.CreateTime CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.CreateTime Get start)

                // *** End programmer edit section *** (LgotaDliaKat.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (LgotaDliaKat.CreateTime Get end)

                // *** End programmer edit section *** (LgotaDliaKat.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.CreateTime Set start)

                // *** End programmer edit section *** (LgotaDliaKat.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (LgotaDliaKat.CreateTime Set end)

                // *** End programmer edit section *** (LgotaDliaKat.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Creator CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Creator Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (LgotaDliaKat.Creator Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Creator Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Creator Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Creator Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.EditTime CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.EditTime Get start)

                // *** End programmer edit section *** (LgotaDliaKat.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (LgotaDliaKat.EditTime Get end)

                // *** End programmer edit section *** (LgotaDliaKat.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.EditTime Set start)

                // *** End programmer edit section *** (LgotaDliaKat.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (LgotaDliaKat.EditTime Set end)

                // *** End programmer edit section *** (LgotaDliaKat.EditTime Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Editor CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Editor Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (LgotaDliaKat.Editor Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Editor Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Editor Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Editor Set end)
            }
        }

        /// <summary>
        /// Oldid.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Oldid CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Oldid CustomAttributes)
        public virtual int Oldid
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Oldid Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Oldid Get start)
                int result = this.fOldid;
                // *** Start programmer edit section *** (LgotaDliaKat.Oldid Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Oldid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Oldid Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Oldid Set start)
                this.fOldid = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Oldid Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Oldid Set end)
            }
        }

        /// <summary>
        /// Льгота для категории.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Osnovanie CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Osnovanie CustomAttributes)
        [PropertyStorage(new string[] {
                "Osnovanie"})]
        public virtual Iis.Eais.Catalogs.StatiaAkta Osnovanie
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Osnovanie Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Osnovanie Get start)
                Iis.Eais.Catalogs.StatiaAkta result = this.fOsnovanie;
                // *** Start programmer edit section *** (LgotaDliaKat.Osnovanie Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Osnovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Osnovanie Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Osnovanie Set start)
                this.fOsnovanie = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Osnovanie Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Osnovanie Set end)
            }
        }

        /// <summary>
        /// Льгота для категории.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Lgota CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Lgota CustomAttributes)
        [PropertyStorage(new string[] {
                "Lgota"})]
        [NotNull()]
        public virtual Iis.Eais.Catalogs.Lgota Lgota
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Lgota Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Lgota Get start)
                Iis.Eais.Catalogs.Lgota result = this.fLgota;
                // *** Start programmer edit section *** (LgotaDliaKat.Lgota Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Lgota Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Lgota Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Lgota Set start)
                this.fLgota = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Lgota Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Lgota Set end)
            }
        }

        /// <summary>
        /// Льгота для категории.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.IstochnikFin CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.IstochnikFin CustomAttributes)
        [PropertyStorage(new string[] {
                "IstochnikFin"})]
        public virtual Iis.Eais.Catalogs.IstochnikFin IstochnikFin
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.IstochnikFin Get start)

                // *** End programmer edit section *** (LgotaDliaKat.IstochnikFin Get start)
                Iis.Eais.Catalogs.IstochnikFin result = this.fIstochnikFin;
                // *** Start programmer edit section *** (LgotaDliaKat.IstochnikFin Get end)

                // *** End programmer edit section *** (LgotaDliaKat.IstochnikFin Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.IstochnikFin Set start)

                // *** End programmer edit section *** (LgotaDliaKat.IstochnikFin Set start)
                this.fIstochnikFin = value;
                // *** Start programmer edit section *** (LgotaDliaKat.IstochnikFin Set end)

                // *** End programmer edit section *** (LgotaDliaKat.IstochnikFin Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку Iis.Eais.Catalogs.LgotKat.
        /// </summary>
        // *** Start programmer edit section *** (LgotaDliaKat.Kategoriia CustomAttributes)

        // *** End programmer edit section *** (LgotaDliaKat.Kategoriia CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Kategoriia"})]
        public virtual Iis.Eais.Catalogs.LgotKat Kategoriia
        {
            get
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Kategoriia Get start)

                // *** End programmer edit section *** (LgotaDliaKat.Kategoriia Get start)
                Iis.Eais.Catalogs.LgotKat result = this.fKategoriia;
                // *** Start programmer edit section *** (LgotaDliaKat.Kategoriia Get end)

                // *** End programmer edit section *** (LgotaDliaKat.Kategoriia Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LgotaDliaKat.Kategoriia Set start)

                // *** End programmer edit section *** (LgotaDliaKat.Kategoriia Set start)
                this.fKategoriia = value;
                // *** Start programmer edit section *** (LgotaDliaKat.Kategoriia Set end)

                // *** End programmer edit section *** (LgotaDliaKat.Kategoriia Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.Catalogs.LgotaDliaKat));
                }
            }

            /// <summary>
            /// "LgotaDliaKat" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LgotaDliaKat
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LgotaDliaKat", typeof(Iis.Eais.Catalogs.LgotaDliaKat));
                }
            }

            /// <summary>
            /// "LgotaDliaKatE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LgotaDliaKatE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LgotaDliaKatE", typeof(Iis.Eais.Catalogs.LgotaDliaKat));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }

    /// <summary>
    /// Detail array of LgotaDliaKat.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLgotaDliaKat CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (DetailArrayDetailArrayOfLgotaDliaKat CustomAttributes)
    public class DetailArrayOfLgotaDliaKat : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (Iis.Eais.Catalogs.DetailArrayOfLgotaDliaKat members)

        // *** End programmer edit section *** (Iis.Eais.Catalogs.DetailArrayOfLgotaDliaKat members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LgotaDliaKat by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LgotaDliaKat.
        /// </summary>
        public DetailArrayOfLgotaDliaKat(Iis.Eais.Catalogs.LgotKat fLgotKat) :
                base(typeof(LgotaDliaKat), ((ICSSoft.STORMNET.DataObject)(fLgotKat)))
        {
        }

        public Iis.Eais.Catalogs.LgotaDliaKat this[int index]
        {
            get
            {
                return ((Iis.Eais.Catalogs.LgotaDliaKat)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(Iis.Eais.Catalogs.LgotaDliaKat dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
