//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;


    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;

    using IIS.Synchronizer;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Страна.
    /// </summary>
    // *** Start programmer edit section *** (Strana CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (Strana CustomAttributes)
    [BusinessServer("Iis.Eais.Catalogs.CatalogsBS, Eais.Catalogs.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Страна")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "PolnoeNaimenovanie as \'Polnoe naimenovanie\'",
            "KratkoeNaimenovanie as \'Kratkoe naimenovanie\'",
            "TcifrKod as \'Tcifr kod\'",
            "BukvKodAlfa2 as \'Bukv kod alfa2\'",
            "BukvKodAlfa3 as \'Bukv kod alfa3\'",
            "Oldid as \'Ид\'"})]
    [View("StranaE", new string[] {
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "PolnoeNaimenovanie as \'Наименование\'",
            "TcifrKod as \'Цифровой код\'",
            "BukvKodAlfa2 as \'Букв. код альфа 2\'",
            "BukvKodAlfa3 as \'Букв. код альфа 3\'",
            "Oldid as \'Ид\'"})]
    [View("StranaL", new string[] {
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "PolnoeNaimenovanie as \'Наименование\'",
            "TcifrKod as \'Цифровой код\'",
            "BukvKodAlfa2 as \'Букв. код альфа 2\'",
            "BukvKodAlfa3 as \'Букв. код альфа 3\'",
            "Oldid as \'Ид\'"})]
    public class Strana : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields, ISync
    {

        private string fPolnoeNaimenovanie;

        private string fKratkoeNaimenovanie;

        private uint fTcifrKod;

        private string fBukvKodAlfa2;

        private string fBukvKodAlfa3;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        private int fOldid;

        // *** Start programmer edit section *** (Strana CustomMembers)

        // *** End programmer edit section *** (Strana CustomMembers)


        /// <summary>
        /// PolnoeNaimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (Strana.PolnoeNaimenovanie CustomAttributes)

        // *** End programmer edit section *** (Strana.PolnoeNaimenovanie CustomAttributes)
        public virtual string PolnoeNaimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (Strana.PolnoeNaimenovanie Get start)

                // *** End programmer edit section *** (Strana.PolnoeNaimenovanie Get start)
                string result = this.fPolnoeNaimenovanie;
                // *** Start programmer edit section *** (Strana.PolnoeNaimenovanie Get end)

                // *** End programmer edit section *** (Strana.PolnoeNaimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.PolnoeNaimenovanie Set start)

                // *** End programmer edit section *** (Strana.PolnoeNaimenovanie Set start)
                this.fPolnoeNaimenovanie = value;
                // *** Start programmer edit section *** (Strana.PolnoeNaimenovanie Set end)

                // *** End programmer edit section *** (Strana.PolnoeNaimenovanie Set end)
            }
        }

        /// <summary>
        /// KratkoeNaimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (Strana.KratkoeNaimenovanie CustomAttributes)

        // *** End programmer edit section *** (Strana.KratkoeNaimenovanie CustomAttributes)
        public virtual string KratkoeNaimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (Strana.KratkoeNaimenovanie Get start)

                // *** End programmer edit section *** (Strana.KratkoeNaimenovanie Get start)
                string result = this.fKratkoeNaimenovanie;
                // *** Start programmer edit section *** (Strana.KratkoeNaimenovanie Get end)

                // *** End programmer edit section *** (Strana.KratkoeNaimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.KratkoeNaimenovanie Set start)

                // *** End programmer edit section *** (Strana.KratkoeNaimenovanie Set start)
                this.fKratkoeNaimenovanie = value;
                // *** Start programmer edit section *** (Strana.KratkoeNaimenovanie Set end)

                // *** End programmer edit section *** (Strana.KratkoeNaimenovanie Set end)
            }
        }

        /// <summary>
        /// TcifrKod.
        /// </summary>
        // *** Start programmer edit section *** (Strana.TcifrKod CustomAttributes)

        // *** End programmer edit section *** (Strana.TcifrKod CustomAttributes)
        public virtual uint TcifrKod
        {
            get
            {
                // *** Start programmer edit section *** (Strana.TcifrKod Get start)

                // *** End programmer edit section *** (Strana.TcifrKod Get start)
                uint result = this.fTcifrKod;
                // *** Start programmer edit section *** (Strana.TcifrKod Get end)

                // *** End programmer edit section *** (Strana.TcifrKod Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.TcifrKod Set start)

                // *** End programmer edit section *** (Strana.TcifrKod Set start)
                this.fTcifrKod = value;
                // *** Start programmer edit section *** (Strana.TcifrKod Set end)

                // *** End programmer edit section *** (Strana.TcifrKod Set end)
            }
        }

        /// <summary>
        /// BukvKodAlfa2.
        /// </summary>
        // *** Start programmer edit section *** (Strana.BukvKodAlfa2 CustomAttributes)

        // *** End programmer edit section *** (Strana.BukvKodAlfa2 CustomAttributes)
        public virtual string BukvKodAlfa2
        {
            get
            {
                // *** Start programmer edit section *** (Strana.BukvKodAlfa2 Get start)

                // *** End programmer edit section *** (Strana.BukvKodAlfa2 Get start)
                string result = this.fBukvKodAlfa2;
                // *** Start programmer edit section *** (Strana.BukvKodAlfa2 Get end)

                // *** End programmer edit section *** (Strana.BukvKodAlfa2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.BukvKodAlfa2 Set start)

                // *** End programmer edit section *** (Strana.BukvKodAlfa2 Set start)
                this.fBukvKodAlfa2 = value;
                // *** Start programmer edit section *** (Strana.BukvKodAlfa2 Set end)

                // *** End programmer edit section *** (Strana.BukvKodAlfa2 Set end)
            }
        }

        /// <summary>
        /// BukvKodAlfa3.
        /// </summary>
        // *** Start programmer edit section *** (Strana.BukvKodAlfa3 CustomAttributes)

        // *** End programmer edit section *** (Strana.BukvKodAlfa3 CustomAttributes)
        public virtual string BukvKodAlfa3
        {
            get
            {
                // *** Start programmer edit section *** (Strana.BukvKodAlfa3 Get start)

                // *** End programmer edit section *** (Strana.BukvKodAlfa3 Get start)
                string result = this.fBukvKodAlfa3;
                // *** Start programmer edit section *** (Strana.BukvKodAlfa3 Get end)

                // *** End programmer edit section *** (Strana.BukvKodAlfa3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.BukvKodAlfa3 Set start)

                // *** End programmer edit section *** (Strana.BukvKodAlfa3 Set start)
                this.fBukvKodAlfa3 = value;
                // *** Start programmer edit section *** (Strana.BukvKodAlfa3 Set end)

                // *** End programmer edit section *** (Strana.BukvKodAlfa3 Set end)
            }
        }

        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Strana.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Strana.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Strana.CreateTime Get start)

                // *** End programmer edit section *** (Strana.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Strana.CreateTime Get end)

                // *** End programmer edit section *** (Strana.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.CreateTime Set start)

                // *** End programmer edit section *** (Strana.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Strana.CreateTime Set end)

                // *** End programmer edit section *** (Strana.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Strana.Creator CustomAttributes)

        // *** End programmer edit section *** (Strana.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Strana.Creator Get start)

                // *** End programmer edit section *** (Strana.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Strana.Creator Get end)

                // *** End programmer edit section *** (Strana.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.Creator Set start)

                // *** End programmer edit section *** (Strana.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Strana.Creator Set end)

                // *** End programmer edit section *** (Strana.Creator Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Strana.EditTime CustomAttributes)

        // *** End programmer edit section *** (Strana.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Strana.EditTime Get start)

                // *** End programmer edit section *** (Strana.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Strana.EditTime Get end)

                // *** End programmer edit section *** (Strana.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.EditTime Set start)

                // *** End programmer edit section *** (Strana.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Strana.EditTime Set end)

                // *** End programmer edit section *** (Strana.EditTime Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Strana.Editor CustomAttributes)

        // *** End programmer edit section *** (Strana.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Strana.Editor Get start)

                // *** End programmer edit section *** (Strana.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Strana.Editor Get end)

                // *** End programmer edit section *** (Strana.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.Editor Set start)

                // *** End programmer edit section *** (Strana.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Strana.Editor Set end)

                // *** End programmer edit section *** (Strana.Editor Set end)
            }
        }

        /// <summary>
        /// Oldid.
        /// </summary>
        // *** Start programmer edit section *** (Strana.Oldid CustomAttributes)

        // *** End programmer edit section *** (Strana.Oldid CustomAttributes)
        public virtual int Oldid
        {
            get
            {
                // *** Start programmer edit section *** (Strana.Oldid Get start)

                // *** End programmer edit section *** (Strana.Oldid Get start)
                int result = this.fOldid;
                // *** Start programmer edit section *** (Strana.Oldid Get end)

                // *** End programmer edit section *** (Strana.Oldid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Strana.Oldid Set start)

                // *** End programmer edit section *** (Strana.Oldid Set start)
                this.fOldid = value;
                // *** Start programmer edit section *** (Strana.Oldid Set end)

                // *** End programmer edit section *** (Strana.Oldid Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.Catalogs.Strana));
                }
            }

            /// <summary>
            /// "StranaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StranaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StranaE", typeof(Iis.Eais.Catalogs.Strana));
                }
            }

            /// <summary>
            /// "StranaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StranaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StranaL", typeof(Iis.Eais.Catalogs.Strana));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
