//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tZaprObekt.
    /// </summary>
    // *** Start programmer edit section *** (tZaprObekt CustomAttributes)

    // *** End programmer edit section *** (tZaprObekt CustomAttributes)
    public enum tZaprObekt
    {

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.Region CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.Region CustomAttributes)
        [Caption("Регион")]
        Region,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.Raion CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.Raion CustomAttributes)
        [Caption("Район")]
        Raion,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.Gorod CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.Gorod CustomAttributes)
        [Caption("Город")]
        Gorod,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.VnutrigorodskaiaTerritoriia CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.VnutrigorodskaiaTerritoriia CustomAttributes)
        [Caption("Внутригородская территория")]
        VnutrigorodskaiaTerritoriia,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.NaselennyiPunkt CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.NaselennyiPunkt CustomAttributes)
        [Caption("Населенный пункт")]
        NaselennyiPunkt,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.Ulitca CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.Ulitca CustomAttributes)
        [Caption("Улица")]
        Ulitca,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.DopolnitelnaiaTerritoriia CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.DopolnitelnaiaTerritoriia CustomAttributes)
        [Caption("Дополнительная территория")]
        DopolnitelnaiaTerritoriia,

        /// <summary>
        ///
        /// </summary>
        // *** Start programmer edit section *** (tZaprObekt.UlitcaDopolnitelnoiTerritorii CustomAttributes)

        // *** End programmer edit section *** (tZaprObekt.UlitcaDopolnitelnoiTerritorii CustomAttributes)
        [Caption("Улица дополнительной территории")]
        UlitcaDopolnitelnoiTerritorii,
    }
}
