//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;


    // *** Start programmer edit section *** (Using statements)
    using Iis.Eais.Common;

    using IIS.Synchronizer;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ВидУдостДок.
    /// </summary>
    // *** Start programmer edit section *** (VidUdostDok CustomAttributes)
    [Primary(true)]
    [Serializable]
    // *** End programmer edit section *** (VidUdostDok CustomAttributes)
    [BusinessServer("Iis.Eais.Catalogs.CatalogsBS, Eais.Catalogs.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Naimenovanie as \'Naimenovanie\'",
            "KratkoeNaimenovanie as \'Kratkoe naimenovanie\'",
            "KodPF as \'Kod PF\'",
            "Prioritet as \'Prioritet\'",
            "KodVidaDokumenta as \'Kod vida dokumenta\'",
            "PrioritetDliaFNS as \'Prioritet dlia FNS\'",
            "TipUdostDok as \'Tip udost dok\'",
            "TipUdostDok.Naimenovanie as \'Naimenovanie\'",
            "Oldid as \'Ид\'"})]
    [View("VidUdostDokEdit", new string[] {
            "Naimenovanie as \'Наименование\'",
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "KodPF as \'Код ПФ\'",
            "TipUdostDok as \'Тип удостоверяющего документа\'",
            "TipUdostDok.Naimenovanie as \'Наименование\'",
            "KodVidaDokumenta as \'Код вида документа, удостоверяющего личность\'",
            "PrioritetDliaFNS as \'Приоритет для ФНС\'",
            "Prioritet as \'Приоритет\'",
            "Oldid as \'Ид\'"})]
    [View("VidUdostDokList", new string[] {
            "Naimenovanie as \'Наименование\'",
            "KratkoeNaimenovanie as \'Краткое наименование\'",
            "KodPF as \'Код ПФ\'",
            "TipUdostDok",
            "TipUdostDok.Naimenovanie as \'Тип удост. док.\'",
            "KodVidaDokumenta as \'Код вида документа\'",
            "PrioritetDliaFNS as \'Приоритет для ФНС\'",
            "Prioritet as \'Приоритет\'",
            "Oldid as \'Ид\'"}, Hidden = new string[] {
            "TipUdostDok"})]
    public class VidUdostDok : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields, ISync
    {

        private string fNaimenovanie;

        private string fKratkoeNaimenovanie;

        private string fKodPF;

        private uint fPrioritet;

        private string fKodVidaDokumenta;

        private uint fPrioritetDliaFNS;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        private int fOldid;

        private Iis.Eais.Catalogs.TipUdostDok fTipUdostDok;

        // *** Start programmer edit section *** (VidUdostDok CustomMembers)

        // *** End programmer edit section *** (VidUdostDok CustomMembers)


        /// <summary>
        /// Naimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.Naimenovanie CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.Naimenovanie CustomAttributes)
        [NotNull()]
        public virtual string Naimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.Naimenovanie Get start)

                // *** End programmer edit section *** (VidUdostDok.Naimenovanie Get start)
                string result = this.fNaimenovanie;
                // *** Start programmer edit section *** (VidUdostDok.Naimenovanie Get end)

                // *** End programmer edit section *** (VidUdostDok.Naimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.Naimenovanie Set start)

                // *** End programmer edit section *** (VidUdostDok.Naimenovanie Set start)
                this.fNaimenovanie = value;
                // *** Start programmer edit section *** (VidUdostDok.Naimenovanie Set end)

                // *** End programmer edit section *** (VidUdostDok.Naimenovanie Set end)
            }
        }

        /// <summary>
        /// KratkoeNaimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.KratkoeNaimenovanie CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.KratkoeNaimenovanie CustomAttributes)
        public virtual string KratkoeNaimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Get start)

                // *** End programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Get start)
                string result = this.fKratkoeNaimenovanie;
                // *** Start programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Get end)

                // *** End programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Set start)

                // *** End programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Set start)
                this.fKratkoeNaimenovanie = value;
                // *** Start programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Set end)

                // *** End programmer edit section *** (VidUdostDok.KratkoeNaimenovanie Set end)
            }
        }

        /// <summary>
        /// KodPF.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.KodPF CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.KodPF CustomAttributes)
        public virtual string KodPF
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.KodPF Get start)

                // *** End programmer edit section *** (VidUdostDok.KodPF Get start)
                string result = this.fKodPF;
                // *** Start programmer edit section *** (VidUdostDok.KodPF Get end)

                // *** End programmer edit section *** (VidUdostDok.KodPF Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.KodPF Set start)

                // *** End programmer edit section *** (VidUdostDok.KodPF Set start)
                this.fKodPF = value;
                // *** Start programmer edit section *** (VidUdostDok.KodPF Set end)

                // *** End programmer edit section *** (VidUdostDok.KodPF Set end)
            }
        }

        /// <summary>
        /// Prioritet.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.Prioritet CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.Prioritet CustomAttributes)
        public virtual uint Prioritet
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.Prioritet Get start)

                // *** End programmer edit section *** (VidUdostDok.Prioritet Get start)
                uint result = this.fPrioritet;
                // *** Start programmer edit section *** (VidUdostDok.Prioritet Get end)

                // *** End programmer edit section *** (VidUdostDok.Prioritet Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.Prioritet Set start)

                // *** End programmer edit section *** (VidUdostDok.Prioritet Set start)
                this.fPrioritet = value;
                // *** Start programmer edit section *** (VidUdostDok.Prioritet Set end)

                // *** End programmer edit section *** (VidUdostDok.Prioritet Set end)
            }
        }

        /// <summary>
        /// KodVidaDokumenta.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.KodVidaDokumenta CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.KodVidaDokumenta CustomAttributes)
        public virtual string KodVidaDokumenta
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.KodVidaDokumenta Get start)

                // *** End programmer edit section *** (VidUdostDok.KodVidaDokumenta Get start)
                string result = this.fKodVidaDokumenta;
                // *** Start programmer edit section *** (VidUdostDok.KodVidaDokumenta Get end)

                // *** End programmer edit section *** (VidUdostDok.KodVidaDokumenta Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.KodVidaDokumenta Set start)

                // *** End programmer edit section *** (VidUdostDok.KodVidaDokumenta Set start)
                this.fKodVidaDokumenta = value;
                // *** Start programmer edit section *** (VidUdostDok.KodVidaDokumenta Set end)

                // *** End programmer edit section *** (VidUdostDok.KodVidaDokumenta Set end)
            }
        }

        /// <summary>
        /// PrioritetDliaFNS.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.PrioritetDliaFNS CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.PrioritetDliaFNS CustomAttributes)
        public virtual uint PrioritetDliaFNS
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.PrioritetDliaFNS Get start)

                // *** End programmer edit section *** (VidUdostDok.PrioritetDliaFNS Get start)
                uint result = this.fPrioritetDliaFNS;
                // *** Start programmer edit section *** (VidUdostDok.PrioritetDliaFNS Get end)

                // *** End programmer edit section *** (VidUdostDok.PrioritetDliaFNS Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.PrioritetDliaFNS Set start)

                // *** End programmer edit section *** (VidUdostDok.PrioritetDliaFNS Set start)
                this.fPrioritetDliaFNS = value;
                // *** Start programmer edit section *** (VidUdostDok.PrioritetDliaFNS Set end)

                // *** End programmer edit section *** (VidUdostDok.PrioritetDliaFNS Set end)
            }
        }

        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.CreateTime CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.CreateTime Get start)

                // *** End programmer edit section *** (VidUdostDok.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (VidUdostDok.CreateTime Get end)

                // *** End programmer edit section *** (VidUdostDok.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.CreateTime Set start)

                // *** End programmer edit section *** (VidUdostDok.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (VidUdostDok.CreateTime Set end)

                // *** End programmer edit section *** (VidUdostDok.CreateTime Set end)
            }
        }

        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.Creator CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.Creator Get start)

                // *** End programmer edit section *** (VidUdostDok.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (VidUdostDok.Creator Get end)

                // *** End programmer edit section *** (VidUdostDok.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.Creator Set start)

                // *** End programmer edit section *** (VidUdostDok.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (VidUdostDok.Creator Set end)

                // *** End programmer edit section *** (VidUdostDok.Creator Set end)
            }
        }

        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.EditTime CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.EditTime Get start)

                // *** End programmer edit section *** (VidUdostDok.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (VidUdostDok.EditTime Get end)

                // *** End programmer edit section *** (VidUdostDok.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.EditTime Set start)

                // *** End programmer edit section *** (VidUdostDok.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (VidUdostDok.EditTime Set end)

                // *** End programmer edit section *** (VidUdostDok.EditTime Set end)
            }
        }

        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.Editor CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.Editor Get start)

                // *** End programmer edit section *** (VidUdostDok.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (VidUdostDok.Editor Get end)

                // *** End programmer edit section *** (VidUdostDok.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.Editor Set start)

                // *** End programmer edit section *** (VidUdostDok.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (VidUdostDok.Editor Set end)

                // *** End programmer edit section *** (VidUdostDok.Editor Set end)
            }
        }

        /// <summary>
        /// Oldid.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.Oldid CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.Oldid CustomAttributes)
        public virtual int Oldid
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.Oldid Get start)

                // *** End programmer edit section *** (VidUdostDok.Oldid Get start)
                int result = this.fOldid;
                // *** Start programmer edit section *** (VidUdostDok.Oldid Get end)

                // *** End programmer edit section *** (VidUdostDok.Oldid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.Oldid Set start)

                // *** End programmer edit section *** (VidUdostDok.Oldid Set start)
                this.fOldid = value;
                // *** Start programmer edit section *** (VidUdostDok.Oldid Set end)

                // *** End programmer edit section *** (VidUdostDok.Oldid Set end)
            }
        }

        /// <summary>
        /// ВидУдостДок.
        /// </summary>
        // *** Start programmer edit section *** (VidUdostDok.TipUdostDok CustomAttributes)

        // *** End programmer edit section *** (VidUdostDok.TipUdostDok CustomAttributes)
        [PropertyStorage(new string[] {
                "TipUdostDok"})]
        [NotNull()]
        public virtual Iis.Eais.Catalogs.TipUdostDok TipUdostDok
        {
            get
            {
                // *** Start programmer edit section *** (VidUdostDok.TipUdostDok Get start)

                // *** End programmer edit section *** (VidUdostDok.TipUdostDok Get start)
                Iis.Eais.Catalogs.TipUdostDok result = this.fTipUdostDok;
                // *** Start programmer edit section *** (VidUdostDok.TipUdostDok Get end)

                // *** End programmer edit section *** (VidUdostDok.TipUdostDok Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (VidUdostDok.TipUdostDok Set start)

                // *** End programmer edit section *** (VidUdostDok.TipUdostDok Set start)
                this.fTipUdostDok = value;
                // *** Start programmer edit section *** (VidUdostDok.TipUdostDok Set end)

                // *** End programmer edit section *** (VidUdostDok.TipUdostDok Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(Iis.Eais.Catalogs.VidUdostDok));
                }
            }

            /// <summary>
            /// "VidUdostDokEdit" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VidUdostDokEdit
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VidUdostDokEdit", typeof(Iis.Eais.Catalogs.VidUdostDok));
                }
            }

            /// <summary>
            /// "VidUdostDokList" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VidUdostDokList
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VidUdostDokList", typeof(Iis.Eais.Catalogs.VidUdostDok));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
