//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Catalogs
{
    using System;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запрос.
    /// </summary>
    // *** Start programmer edit section *** (Zapros CustomAttributes)
    [Serializable]
    // *** End programmer edit section *** (Zapros CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [Caption("Запрос")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ZaprosE", new string[] {
            "ZaprObekt as \'Запрашиваемый объект\'",
            "Territoriia as \'Принадлежность к территории\'",
            "Territoriia.NaimDlyaZaprosa",
            "Ulitca as \'Принадлежность к улице\'",
            "Ulitca.NaimDlyaZaprosa"}, Hidden = new string[] {
            "Territoriia.NaimDlyaZaprosa",
            "Ulitca.NaimDlyaZaprosa"})]
    public class Zapros : ICSSoft.STORMNET.DataObject
    {

        private Iis.Eais.Catalogs.tZaprObekt fZaprObekt;

        private Iis.Eais.Catalogs.Ulitca fUlitca;

        private Iis.Eais.Catalogs.Territoriia fTerritoriia;

        // *** Start programmer edit section *** (Zapros CustomMembers)

        // *** End programmer edit section *** (Zapros CustomMembers)


        /// <summary>
        /// ZaprObekt.
        /// </summary>
        // *** Start programmer edit section *** (Zapros.ZaprObekt CustomAttributes)

        // *** End programmer edit section *** (Zapros.ZaprObekt CustomAttributes)
        [NotNull()]
        public virtual Iis.Eais.Catalogs.tZaprObekt ZaprObekt
        {
            get
            {
                // *** Start programmer edit section *** (Zapros.ZaprObekt Get start)

                // *** End programmer edit section *** (Zapros.ZaprObekt Get start)
                Iis.Eais.Catalogs.tZaprObekt result = this.fZaprObekt;
                // *** Start programmer edit section *** (Zapros.ZaprObekt Get end)

                // *** End programmer edit section *** (Zapros.ZaprObekt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zapros.ZaprObekt Set start)

                // *** End programmer edit section *** (Zapros.ZaprObekt Set start)
                this.fZaprObekt = value;
                // *** Start programmer edit section *** (Zapros.ZaprObekt Set end)

                // *** End programmer edit section *** (Zapros.ZaprObekt Set end)
            }
        }

        /// <summary>
        /// Запрос.
        /// </summary>
        // *** Start programmer edit section *** (Zapros.Ulitca CustomAttributes)

        // *** End programmer edit section *** (Zapros.Ulitca CustomAttributes)
        [PropertyStorage(new string[] {
                "Ulitca"})]
        public virtual Iis.Eais.Catalogs.Ulitca Ulitca
        {
            get
            {
                // *** Start programmer edit section *** (Zapros.Ulitca Get start)

                // *** End programmer edit section *** (Zapros.Ulitca Get start)
                Iis.Eais.Catalogs.Ulitca result = this.fUlitca;
                // *** Start programmer edit section *** (Zapros.Ulitca Get end)

                // *** End programmer edit section *** (Zapros.Ulitca Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zapros.Ulitca Set start)

                // *** End programmer edit section *** (Zapros.Ulitca Set start)
                this.fUlitca = value;
                // *** Start programmer edit section *** (Zapros.Ulitca Set end)

                // *** End programmer edit section *** (Zapros.Ulitca Set end)
            }
        }

        /// <summary>
        /// Запрос.
        /// </summary>
        // *** Start programmer edit section *** (Zapros.Territoriia CustomAttributes)

        // *** End programmer edit section *** (Zapros.Territoriia CustomAttributes)
        [PropertyStorage(new string[] {
                "Territoriia"})]
        public virtual Iis.Eais.Catalogs.Territoriia Territoriia
        {
            get
            {
                // *** Start programmer edit section *** (Zapros.Territoriia Get start)

                // *** End programmer edit section *** (Zapros.Territoriia Get start)
                Iis.Eais.Catalogs.Territoriia result = this.fTerritoriia;
                // *** Start programmer edit section *** (Zapros.Territoriia Get end)

                // *** End programmer edit section *** (Zapros.Territoriia Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Zapros.Territoriia Set start)

                // *** End programmer edit section *** (Zapros.Territoriia Set start)
                this.fTerritoriia = value;
                // *** Start programmer edit section *** (Zapros.Territoriia Set end)

                // *** End programmer edit section *** (Zapros.Territoriia Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ZaprosE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ZaprosE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ZaprosE", typeof(Iis.Eais.Catalogs.Zapros));
                }
            }
        }
    }
}
