//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iis.Eais.Leechnost
{
    using System;


    // *** Start programmer edit section *** (Using statements)
    using System.Collections.Generic;
    using Iis.Eais.Common.Errors;
    using Iis.Eais.Leechnost.Helpers;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ProzhivanieBS.
    /// </summary>
    // *** Start programmer edit section *** (ProzhivanieBS CustomAttributes)

    // *** End programmer edit section *** (ProzhivanieBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ProzhivanieBS : Iis.Eais.Common.CommonBS
    {

        // *** Start programmer edit section *** (ProzhivanieBS CustomMembers)
        public override List<IError> CanDelete(Type type, Guid objectId)
        {
            List<IError> errors = new List<IError>();

            // Проверка связанных объектов по списку
            errors.AddRange(CheckRelationsBeforDelete(objectId, RelationsToCheckBeforeDelete.Prozhivanie));

            return errors;
        }
        // *** End programmer edit section *** (ProzhivanieBS CustomMembers)


        // *** Start programmer edit section *** (OnUpdateProzhivanie CustomAttributes)

        // *** End programmer edit section *** (OnUpdateProzhivanie CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateProzhivanie(Iis.Eais.Leechnost.Prozhivanie UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateProzhivanie)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateProzhivanie)
        }
    }
}
